subscriptions-project/swg-js

src/runtime/pay-flow-test.js
src/runtime/pay-flow.js

Support additional {details} format for pay response

---

docs/offers-flow.md
src/api/subscriptions.js
src/runtime/offers-flow-test.js
src/runtime/offers-flow.js
src/runtime/runtime-test.js
src/runtime/runtime.js

/cc @alaskajim @ratana for doc updates

Subscribe option flow

---

src/components/dialog.js
src/runtime/entitlements-manager-test.js
src/runtime/entitlements-manager.js
src/runtime/offers-flow.js
src/ui/toast-test.js
src/ui/toast.js

TODO:
Use the 'source' parameter passed to the Activity to show correct publisher.

Toast iframe implementation

---

docs/offers-flow.md
src/api/subscriptions.js
src/runtime/offers-flow-test.js
src/runtime/offers-flow.js
src/runtime/runtime-test.js
src/runtime/runtime.js

/cc @ratana @alaskajim for API/docs

API and passthrough for offer options: list + skus

---

src/model/page-config-resolver-test.js
src/model/page-config-resolver.js

Parses Microdata in a page to retrieve the product ID and access information

Microdata (#318)

---

package.json

See https://github.com/google/web-activities/releases/tag/1.8

Upgrade Web Activities to 1.8

---

src/api/subscriptions.js
src/runtime/offers-flow-test.js
src/runtime/offers-flow.js
src/runtime/runtime-test.js

This change has corresponding CL.

Allow optional close action for Offers View

---

package.json

https://github.com/google/web-activities/releases/tag/1.9

Web Activities 1.9

---

docs/buttons.md
docs/core-apis.md
examples/sample-pub/publisher.js
examples/sample-pub/sample-pub-app.js
src/api/subscriptions.js
src/runtime/button-api-test.js
src/runtime/button-api.js
src/runtime/runtime-test.js
src/runtime/runtime.js

Create/attach button API

---

src/runtime/link-accounts-flow.js
src/runtime/offers-flow-test.js
src/runtime/pay-flow-test.js
src/runtime/pay-flow.js
src/utils/activity-utils-test.js
src/utils/activity-utils.js

+ minor refactoring to disambiguate some related APIs

Require encrypted payload for redirects

---

package.json

See https://github.com/google/web-activities/releases/tag/1.13

Web Activities 1.13

---

build-system/tasks/export-to-es.js
src/api/user-data.js
src/components/dialog.js
src/components/view.js
src/runtime/deferred-account-flow.js
src/runtime/link-accounts-flow.js
src/runtime/pay-flow.js
src/ui/loading-view.js
src/ui/toast.js
src/utils/dom.js
src/utils/jwt.js
src/utils/log.js
src/utils/style.js

FIXIT summit - Fix lint warnings

---

src/runtime/login-notification-api-test.js
src/runtime/login-notification-api.js
src/runtime/login-prompt-api-test.js
src/runtime/login-prompt-api.js

refactor both login api's to point to the same iframe

---

src/utils/animation-test.js

https://travis-ci.org/subscriptions-project/swg-js/builds/408638328?utm_source=github_status&utm_medium=notification

fixing animation_test bug

---

src/api/subscribe-response.js
src/runtime/api-test.js
src/runtime/deferred-account-flow-test.js
src/runtime/deferred-account-flow.js
src/runtime/pay-flow-test.js
src/runtime/pay-flow.js

Accept id_token and entitlements from the payment response

---

src/runtime/pay-flow.js
src/runtime/runtime-test.js

Reverts subscriptions-project/swg-js#404

Revert "Disable pay prefetch"

---

docs/deferred-account-flow.md

Remove "entitlements" and add "purchaseData"

Fix deferred account creation doc

---

docs/link-flow.md

Add return to saveSubscription example

Fix link flow doc

---

docs/login-flow.md

The correct function name is showLoginNotification and has no response

Login Flow doc - Fix function name

---

src/runtime/deferred-account-flow-test.js
src/runtime/deferred-account-flow.js

Fix the incorrect messaging binding.

---

docs/core-apis.md
src/api/subscriptions.js
src/runtime/entitlements-manager-test.js
src/runtime/entitlements-manager.js
src/runtime/runtime-test.js
src/runtime/runtime.js

Provide a clear API to clear the state and cache

---

src/runtime/experiment-flags.js
src/runtime/pay-client-test.js
src/runtime/pay-client.js

Define and propagate native payments experiment

---

package.json

https://github.com/google/web-activities/releases/tag/1.16

Web Activities 1.16

---

docs/deferred-account-flow.md

DAC: minor update to the docs

---

src/runtime/pay-flow-test.js
src/runtime/pay-flow.js

ACTION_PAYMENT_COMPLETE
ACTION_ACCOUNT_CREATED
ACTION_ACCOUNT_ACKNOWLEDGED

Analytics Logging

---

docs/embed-client.md

Update src URL for swg.js in embed-client.md

Update SwG Client doc

---

docs/core-apis.md

Update guidance for subscriptions object reset and clear features

Update doc: clear and reset guidance

---

docs/entitlements-flow.md

Include section on validating entitlements JWT

---

src/model/page-config-resolver-test.js
src/model/page-config-resolver.js

Expand allowed types
fixes https://github.com/ampproject/amphtml/issues/20747

Expand allowed @type values

---

src/api/subscriptions.js
src/runtime/contributions-flow.js
src/runtime/pay-flow-test.js
src/runtime/pay-flow.js
src/runtime/runtime-test.js
src/runtime/runtime.js

Added contribution API (Experimental)
```
subscriptions.contribute(sku);
```
TODO:
Need to update the Payment confirmation views on gPay complete.

Contribution UI

---

src/runtime/contributions-flow-test.js
src/runtime/contributions-flow.js
src/runtime/offers-flow-test.js
src/runtime/offers-flow.js

This parameter will be used internally to filter correct SKUs.

Add productType parameter to offers and contributions flow

---

src/api/propensity-api.js
src/api/subscriptions.js
src/runtime/experiment-flags.js
src/runtime/propensity-test.js
src/runtime/propensity.js
src/runtime/runtime-test.js
src/runtime/runtime.js

Propensity API available to the publisher from SwG

Propensity API

---

docs/buttons.md
docs/contributions-flow.md
docs/deferred-account-flow.md
docs/embed-client.md
docs/entitlements-flow.md
docs/link-flow.md
docs/login-flow.md
docs/offers-flow.md
docs/page-markup.md
docs/subscribe-flow.md

Before:
```
function hello() {
console.log("Hello world");
}
```
After:
```js
function hello() {
console.log("Hello world");
}
```

Docs: Syntax highlighting for code examples

---

src/runtime/propensity-test.js
src/runtime/propensity.js

Provide correct error message in Propensity API

---

exports/swg.js

This is very small, I need some enums in AMP that didn't get sent there during the initial Event Manager push.

export enums for amp

---

src/runtime/analytics-service.js
src/runtime/button-api-test.js
src/runtime/button-api.js
src/runtime/runtime-test.js
src/runtime/runtime.js
src/runtime/smart-button-api.js

Reverts subscriptions-project/swg-js#555

Revert "Adds Impression Logging for SwG Button and SmartBox"

---

src/runtime/client-event-manager-test.js
src/runtime/client-event-manager.js
src/runtime/runtime-test.js
src/runtime/runtime.js

This instantiates the event manager sooner in the pipeline and guards the event broadcasting behind the configured runtime promise to ensure events that occur early in the pipeline wait until everything is ready before attempting to log anything.

Event Manager / Available Sooner / Log Behind Promise

---

examples/sample-pub/publisher.js

Creates button element for SmartButton demo automatically as needed, to make development on the SmartButton a bit easier.

Creates button element for SmartButton demo

---

exports/swg.js

This reverts commit 0754b7b4ef683c4dfe403f9528278638c30fda54.

Revert "export event manager"

---

src/runtime/analytics-service.js
src/runtime/button-api-test.js
src/runtime/smart-button-api.js

Add impression logging to the SmartBox using AnalyticsService.

Smartbox Impression Logging

---

build-system/exec.js
build-system/git.js
build-system/tasks/lint.js
build-system/travis.js
gulpfile.js
package.json
yarn.lock

Updates `lint` task based on the one in `amphtml`. This will allow us to use the `--local_changes` flag, and will hopefully make it easier to bring over other improvements in the future, like including `prettier` for formatting.

🏗️ Updates lint task

---

src/utils/xhr.js

Removes extra TODO

---

src/runtime/offers-flow-test.js
src/runtime/offers-flow.js

Adds impression logging for offers flow to OffersFlow using EventManager. Adds tests.

Adds logging of IMPRESSION_OFFERS to offers-flow.js

---

src/proto/api_messages_test.js
src/runtime/contributions-flow-test.js
src/runtime/contributions-flow.js
src/runtime/offers-flow-test.js
src/runtime/offers-flow.js
src/ui/activity-iframe-view-test.js
src/ui/activity-iframe-view.js

These are hidden behind an experiment.

Project Hejira: use on() and execute() APIs in Offers and Contributions flows

---

contributing/DEVELOPING.md

Adds section to DEVELOPING docs which mentions how to automatically format code using a `gulp` command and a VSCode plugin

📖 Adds Code quality & style section to docs

---

build-system/tasks/compile.js

🏗 Improves syntax error logging

---

src/runtime/analytics-service.js
src/runtime/runtime.js

Determine if a new service iframe error is caused by starting the service too soon.

Stop starting server so soon

---

src/runtime/analytics-service-test.js
src/runtime/analytics-service.js

This allows us to know someone is in AMP.

Always log page load event

---

src/runtime/button-api-test.js
src/runtime/smart-button-api.js

1) Ensure SmartButton uses addDefaultArguments
2) Re-factor button-api tests for code efficiency and to prepare for future changes

Refactor to prep for future changes

---

src/runtime/experiment-flags.js
src/runtime/runtime-test.js
src/runtime/runtime.js

DEPRECATE the contributions experimental flag.

Remove experiment flag for Contributions

---

build-system/config.js
build-system/tasks/check-rules.js

Updates test regex patterns to include the big `src/proto/api_messages_test.js` test

♻ Registers `src/proto/api_messages_test.js` as a test

---

src/runtime/pay-flow-test.js
src/runtime/pay-flow.js

oneTime should actually have been paymentRecurrence

Change so Contribution's one-time feature is understandable by Pay

---

src/runtime/offers-flow-test.js
src/runtime/offers-flow.js

Pass additional data to the send offers flow in swg so that this information can be sent to Propensity.

Send offers to flow

---

src/api/subscribe-response.js
src/runtime/api-test.js
src/runtime/deferred-account-flow.js
src/runtime/pay-client-test.js
src/runtime/pay-client.js
src/runtime/pay-flow-test.js
src/runtime/pay-flow.js

Reverts subscriptions-project/swg-js#878
Reverting because SubscribeResponse shouldn't be changed. Particularly my removal of productType which is documented publicly:
https://github.com/subscriptions-project/swg-js/blob/master/docs/subscribe-flow.md#subscribe-response

Revert "Preserve paymentRequest locally."

---

src/runtime/experiment-flags.js
src/runtime/pay-client-test.js
src/runtime/pay-client.js

Native has been at 100% for awhile now.

Clean up gpay_native experiment.

---

src/runtime/pay-flow-test.js
src/runtime/pay-flow.js

Redo of PR 821 (https://github.com/subscriptions-project/swg-js/pull/821)
Test currently doesn't pass even though console logs show a different behavior than what the test seems to be seeing - trying to figure out why.

Trigger flow fix

---

build-system/tasks/karma.conf.js
src/runtime/callbacks-test.js
src/runtime/pay-flow-test.js

Sets Pay environment var for Karma tests, which will allow for future optimizations.
Also increases coverage to 100% for a few tests.

🏗 Sets Pay environment in Karma tests

---

build-system/tasks/karma.conf.js

✅ Replaces `$payEnvironment$` variable with "TEST" for Karma tests

---

test/e2e/pages/login.js

This should increase the success rate of E2E retries, at least locally. I noticed some E2E retries failing because they would get stuck trying to sign in when they were already signed in.

✅ Skips E2E login step if possible

---

docs/contributions-flow.md

I noticed this documentation was a little outdated compared to https://developers.google.com/news/subscribe/guides/offer-contributions-on-web, so I made a few updates. Let me know what you think :smile:

📖 Suggests using setOnPaymentResponse method

---

src/model/page-config-resolver.js

Closes https://github.com/ampproject/amphtml/issues/24247

Mark "no config could be discovered" as a user error

---

exports/swg.js

This change is to help testing the porting of the deferred account creation flow in the AMP project.

Export deferred account creation classes

---

exports/swg.js

This PR fixes the `export-to-amp` gulp task

🐛 Fixes imports for `export-to-amp` task

---

src/api/subscribe-response.js
src/runtime/pay-flow.js

Also formats some JS with Prettier

Fixing compilation blockers

---

build-system/tasks/check-rules.js
src/runtime/logger-test.js
src/runtime/propensity-server-test.js
src/runtime/propensity-test.js

Also includes some Prettier formatting changes that VS Code automatically applied

♻️ Uses the term allowlist instead of whitelist

---

src/runtime/pay-client.js

Remove whitespaces from pay-client.js

Remove whitespaces from pay-client.js

---

src/runtime/pay-client.js

Remove @const from this.pay_client_ in pay-client.js

Remove @const from this.pay_client_

---

src/api/client-event-manager-api.js
src/api/deferred-account-creation.js
src/api/entitlements.js
src/api/user-data.js

This PR makes no functional changes

Formats code with prettier

---

examples/sample-pub/publisher.js

I updated a couple comments based on your post-merge suggestions in #1234

Improves comments

---

src/api/subscriptions.js
src/runtime/runtime-test.js
src/runtime/runtime.js

The new Metering Regwall script needs to trigger the login request

Adds triggerLoginRequest method to Subscriptions API

---

src/utils/gaa.js

- Makes GSI button full-width
- Hides "No thanks" button
---

Regwall style updates

---

build-system/extern.js
build-system/tasks/check-rules.js
examples/google-signin/google-signed-in-redirect.html
examples/google-signin/google-signin-redirect.html
examples/sample-pub/metering.js
examples/sample-pub/publisher.js
examples/sample-pub/sample-pub-app.js
examples/sample-pub/views/article.html
src/utils/gaa-test.js
src/utils/gaa.js

This PR simplifies the Regwall's GSI implementation to improve its compatibility with gNews' embedded webviews.

Simplifies Regwall's GSI implementation

---

examples/sample-pub/metering.js
examples/sample-pub/publisher.js
src/utils/gaa.js

Thanks for this idea, @ed-bird !

Regwall: Gets publisher name from page config

---

examples/sample-pub/metering.js
examples/sample-pub/publisher.js
src/utils/gaa-test.js
src/utils/gaa.js

This PR will help me verify the flow E2E in the GNews app

Regwall: Switches to GSI's "popup" mode (without iframe shim for now)

---

.travis.yml

The sign-in flow changed and our team is waiting on a workaround

Temporarily disables E2E tests

---

src/model/page-config-resolver-test.js
src/model/page-config-resolver.js

Page Config Parser: Allow top level array of objects

---

src/utils/gaa-test.js
src/utils/gaa.js

Also cleans up some existing tests

GAA: Adds test for sending intro post message

---

src/utils/gaa-test.js
src/utils/gaa.js

This PR improves accessibility for people using screenreaders
- Focus shifts to the Regwall's after it animates in
- The Regwall is marked up as a dialog/modal
- Logo image gets an alt attribute
- Key elements are given `tabindex` attributes (all of "0" as is best practice, to allow screenreaders to determine order)

GAA: Improves accessibility

---

contributing/pr-release-checker/README.md
contributing/pr-release-checker/index.html
contributing/pr-release-checker/pr-release-checker.js

This PR adds a tool that tells you whether a given swg-js PR is released on Web and AMP

PR Release Checker

---

src/utils/url-test.js
src/utils/url.js

These were separated out of a larger PR being reviewed by John.

Create some URL helpers

---

src/components/dialog-manager-test.js
src/components/dialog-manager.js
src/components/dialog.js
src/runtime/entitlements-manager-test.js
src/runtime/meter-toast-api-test.js
src/runtime/meter-toast-api.js

Modifies MeterToastApi so that we will have a smaller loading screen for the desktop iframe that matches the resulting size of the iframe.

Change size of loading iframe for meter toast.

---

src/utils/gaa-test.js
src/utils/gaa.js

This PR makes the Regwall disable scrolling while it's open

Showcase Regwall: Disable scrolling

---

src/proto/api_messages-test.js
src/proto/api_messages.js

Adds nonce to EntitlementsRequest proto.

Add nonce to EntitlementsRequest

---

examples/sample-pub/publisher.js

Credit goes to @ed-bird for finding this https://github.com/subscriptions-project/scenic-demo/pull/231

Fixes referrer check in Showcase demo

---

src/utils/gaa-test.js
src/utils/gaa.js
src/utils/i18n.js

The Google Sign-In button won't localize itself :shrug:

Showcase Regwall: Localizes Google Sign-In button

---

docs/subscribe-flow.md

Based on https://github.com/andrehash/swg-js/commit/9f4cfba206d8fab20ef2fd3db970e0c92adc5272

Describe entitlements object (thanks andrehash@!)

---

src/utils/gaa.js

I missed this from https://github.com/subscriptions-project/swg-js/pull/1511

Use msg for GSI button content

---

package.json

This PR allows older Yarn versions, like we did before #1552 (merged today)

Allows older Yarn versions

---

src/runtime/entitlements-manager.js

You suggested using this method in another PR, and it seems like it would work well here too

Entitlements Manager: Uses addQueryParam when possible

---

src/api/subscriptions.js
src/runtime/event-type-mapping.js

This makes b/181690059 API complete

Create publisher facing showcase ineligible event

---

src/polyfills/promise.js

This PR updates our Promise polyfill to match `amphtml`'s 
https://github.com/ampproject/amphtml/blob/main/src/polyfills/promise.js
This fixes an issue in IE11

Update Promise polyfill

---

assets/swg-button.css
assets/swg-mini-prompt.css

- Fix mini prompt sizing for small screens
- Adjust dark mode color
- Adjust button padding and sizing

Mini prompt and button UX tweaks

---

package.json
yarn.lock

Note: [Codecov says](https://github.com/codecov/codecov-node/issues/298#issuecomment-820601347) their `codecov` npm package wasn't affected by the [Bash Uploader breach](https://about.codecov.io/security-update/) they announced today

Remove extra deps

---

src/runtime/pay-client-test.js
src/runtime/pay-client.js

Initializes Pay Client in ctor upon redirect. Hides changes behind an experiment to ensure it works in production. Adds unit tests.

Initialize Pay Client in ctor upon redirect.

---

src/api/basic-subscriptions.js
src/runtime/basic-runtime.js

Reverts subscriptions-project/swg-js#1626

Revert "Add setOnLoginRequest to BasicRuntime init()"

---

src/utils/gaa-test.js
src/utils/gaa.js

@ed-bird requested a warning message when a publisher passes an invalid origin to our Showcase Google-Sign In button `show` method

Showcase: Fails and warns when passed invalid origins

---

src/api/subscriptions.js
src/proto/api_messages.js
src/runtime/runtime-test.js
src/runtime/runtime.js

Create the shell of AudienceActions API.
This API provides the best action to engage the audience for a publisher considering audience's propensity and context.

Create dummy API of AudienceActions.

---

src/utils/xhr-test.js
src/utils/xhr.js

This PR removes an unused method and adds tests

Add coverage to src/utils/xhr.js

---

src/components/dialog-test.js
src/components/dialog.js

- Add tests
- Remove dead code

Dialog: Improves test coverage

---

examples/sample-pub/styles.css

Showcase: Styles reset metering demo button.

---

assets/swg-button.css

Add missing background color for dark button interactive states

Dark button interactive states

---

src/utils/gaa.js

This PR helps prepare for some new logging

Showcase: Refactoring calls to Swgjs

---

src/runtime/entitlements-manager.js
src/utils/gaa-test.js
src/utils/gaa.js

We want to send the pingback on all logging events, regardless to if gaa_at == na.

Don't Validate Access Type during Pingback Logging

---

src/utils/gaa.js

Showcase: Gives Regwall a gradient background

---

shortcuts.sh

This PR creates some initial Bash shortcuts. Hopefully these will make Swgjs development easier, especially for engineers newer to Nodejs and/or Git(Hub)
Over time, I hope to improve these shortcuts, and update documentation to reference them

Creates Bash shortcuts

---

src/components/graypane.js
src/utils/gaa.js

I bet users will appreciate this. It already makes demos easier to use

Let users click through Paywall/Regwall backgrounds

---

assets/i18n/strings/en_GB.xlb
examples/sample-pub/publisher.js
src/i18n/strings.js
src/utils/gaa-test.js
src/utils/gaa.js

This PR adds an optional CASL blurb
Additional translations will come in a follow-up PR

Showcase: Optionally render CASL blurb

---

src/runtime/entitlements-manager-test.js
src/runtime/entitlements-manager.js

Set isUserRegistered = true for google subscriber entitlements. This is used in log statements and better matches the definition of "isUserRegistered".

Set isUserRegistered = true for google subscriber entitlements

---

src/runtime/experiment-flags.js
src/ui/activity-iframe-view-test.js
src/ui/activity-iframe-view.js

This PR cleans up a scrolling experiment. Turns out the fix is outside of Swgjs

Removes scrolling experiment

---

src/components/dialog.css

This PR updates the Toast's styles

Toast: Updated styles

---

.babelrc
build-system/config.js
build-system/tasks/closure-compile.js
build-system/tasks/compile.js
package.json
src/basic-main.js
src/main.js
src/polyfills.js
src/polyfills/array-includes-test.js
src/polyfills/array-includes.js
src/polyfills/document-contains-test.js
src/polyfills/document-contains.js
src/polyfills/domtokenlist-toggle-test.js
src/polyfills/domtokenlist-toggle.js
src/polyfills/math-sign-test.js
src/polyfills/math-sign.js
src/polyfills/object-assign-test.js
src/polyfills/object-assign.js
src/polyfills/object-values-test.js
src/polyfills/object-values.js
src/polyfills/promise-test.js
src/polyfills/promise.js
src/utils/url.js
test/_init_tests.js
yarn.lock

Reverts subscriptions-project/swg-js#1834
We gotta wait until September :cry:

Revert "Removes IE11 support"

---

src/runtime/pay-client.js

Allow #swg.mode to override pay environment

Add swg.mode support to payclient

---

src/proto/api_messages.js
src/runtime/entitlements-manager-test.js
src/runtime/entitlements-manager.js

This PR follows up on #1897, and logs a special event when unlocking for crawlers, instead of logging nothing

Analytics: Logs special event when unlocking for crawlers

---

demos/public/demos.js
demos/public/qual/contributions/autoprompt-free.html
demos/public/qual/contributions/autoprompt-paywalled.html
demos/public/qual/contributions/button-dark.html
demos/public/qual/contributions/button-french.html
demos/public/qual/contributions/button-light.html
demos/public/qual/contributions/free-article.html
demos/public/qual/contributions/index.html

Publishers can access these `qual` pages by opening this URL:
http://localhost:8000/demos/public/qual/contributions/index.html

Demos: Add qual pages

---

src/proto/api_messages-test.js
src/proto/api_messages.js

Used to notify that a dialog should be opened for the specified URL path

Include OpenDialogRequest in api_messages

---

demos/public/prod/subscriptions/autoprompt-free.html
demos/public/prod/subscriptions/autoprompt-paywalled.html
demos/public/prod/subscriptions/button-dark.html
demos/public/prod/subscriptions/button-french.html
demos/public/prod/subscriptions/button-light.html
demos/public/prod/subscriptions/free-article.html
demos/public/prod/subscriptions/index.html
demos/public/qual/subscriptions/autoprompt-free.html
demos/public/qual/subscriptions/autoprompt-paywalled.html
demos/public/qual/subscriptions/button-dark.html
demos/public/qual/subscriptions/button-french.html
demos/public/qual/subscriptions/button-light.html
demos/public/qual/subscriptions/free-article.html
demos/public/qual/subscriptions/index.html

This PR adds prod and qual subscription demos

Demos: Subscriptions

---

src/model/page-config-resolver-test.js
src/model/page-config-resolver.js

Check the graph entry in the JSON-LD for the page config.

---

docs/CODEOWNERS

…which allows us to remove most of the per-file owners.
This is a followup to https://github.com/subscriptions-project/swg-js/pull/1968.

Add myself as a global codeowner

---

src/utils/gaa.js

Use important rule for Showcase CSS

---

src/runtime/basic-runtime.js
src/runtime/entitlements-manager-test.js
src/runtime/entitlements-manager.js

This PR lets SwG Basic listen for entitlements

Fix Entitlements callback for SwG Basic

---

.github/workflows/ci.yaml
package.json
test/e2e/nightwatch.conf.js
yarn.lock

- Use latest chromedriver for local (assuming latest browser installed)
- GitHub CI isn't always at latest, but use environment var instead for that case to pick the right one
- Clean up the other driver loading

Upgrade Chromedriver for local and use environment version for CI

---

demos/public/prod/inactive/autoprompt-free.html
demos/public/prod/inactive/autoprompt-large-free.html
demos/public/prod/inactive/autoprompt-paywalled.html
demos/public/prod/inactive/button-dark.html
demos/public/prod/inactive/button-french.html
demos/public/prod/inactive/button-light.html
demos/public/prod/inactive/free-article.html
demos/public/prod/inactive/index.html

https://swgjs-demos.wl.r.appspot.com/prod/inactive/button-light.html

Demonstrate an inactive publication

---

src/utils/xhr.js

Clarify the CORS error explainer text

Clarify CORS messages

---

src/i18n/swg-strings.js

Add zh-cn, zh-hk strings for SwG

i18n: Add zh-cn, zh-hk strings for SwG

---

src/utils/gaa-test.js
src/utils/gaa.js

This PR updates the Showcase code to use async/await instead of chaining promises

Showcase: Use async/await

---

build-system/eslint-rules/no-global.js

This PR should help us upgrade the `eslint` NPM module

Remove dependency on private 3P method of `eslint` NPM module

---

src/utils/gaa-test.js
src/utils/gaa.js

This reverts https://github.com/subscriptions-project/swg-js/pull/2053.
Async/await is not supported in amphtml yet.

Revert "Showcase: Use async/await (#2053)"

---

src/runtime/audience-action-flow-test.js
src/runtime/audience-action-flow.js
src/runtime/auto-prompt-manager-test.js
src/runtime/auto-prompt-manager.js
src/runtime/entitlements-manager.js

Sets up the auto-prompt-manager to recognize provided audience actions, allowing a prompt for a user to complete a flow for additional entitlements

Handling actions in autoprompt

---

src/proto/api_messages-test.js
src/proto/api_messages.js

This is used for checking if the user has completed an audience action.

Add CompleteAudienceActionResponse to the API message

---

src/runtime/client-config-manager-test.js
src/runtime/client-config-manager.js

Fixing: that moment when I cut and paste my typo to the tests which means that the tests don't catch the typo.

typos-r-us

---

src/i18n/swg-strings.js

This PR updates the "Contribute with..." string for pt-br, as referenced in http://b/209442815

Update "Contribute with..." string for pt-br

---

demos/public/prod/subscriptions/autoprompt-free.html
demos/public/prod/subscriptions/autoprompt-large-free.html
demos/public/prod/subscriptions/autoprompt-paywalled.html
demos/public/prod/subscriptions/button-dark.html
demos/public/prod/subscriptions/button-french.html
demos/public/prod/subscriptions/button-light.html
demos/public/prod/subscriptions/free-article.html

This PR updates the prod subscriptions demo to use a new publication ID and product name

Demos: Prod Subscriptions

---

src/i18n/swg-strings.js

This PR updates a `pt` translation for "Contribute with Google" text (b/209442815)

Update pt translation

---

.storybook/main.js
src/stories/ContributeButton.stories.js
src/stories/SubscribeButton.stories.js

This PR adds a story for the Subscribe and Contribute buttons

Add stories for buttons

---

src/components/dialog-test.js
src/components/dialog.css
src/components/dialog.js
src/runtime/contributions-flow-test.js
src/runtime/contributions-flow.js
src/runtime/offers-flow-test.js
src/runtime/offers-flow.js
src/ui/activity-iframe-view-test.js
src/ui/activity-iframe-view.js

Internal tracking: b/227460883

Disable content scrolling when offers dialog is visible

---

src/model/auto-prompt-config.js
src/runtime/client-config-manager.js
src/runtime/offers-flow-test.js
src/runtime/offers-flow.js

Forward purchaseUnavailableRegion flag to subscriptions iframe

---

src/model/auto-prompt-config.js
src/model/client-config.js
src/runtime/auto-prompt-manager-test.js
src/runtime/client-config-manager.js

Move UiPredicates class to client-config.js

---

src/proto/api_messages.js

Adds ACTION_TYPE_UPDATE_COUNTER to notify the host to update the counter after a submission.

Update api_messages.js with generated changes adding a new ActionType

---

src/i18n/swg-strings.js

Internal reference: b/228316235

Add translation for two strings

---

src/runtime/basic-runtime-test.js
src/runtime/basic-runtime.js

Internal reference: b/229882364

Clicking become a subscriber on meter prompt should not block content

---

src/utils/gaa-test.js
src/utils/gaa.js

Applied new analytics event to regwall button

---

src/utils/gaa-test.js
src/utils/gaa.js

Click event logging is currently absent now updating code to log it representing one of the flows (#1) for b/232215758.
This change deals handles redirect with a delay of very short/unperceivable time using setTimeout.

Logging 3P button click with new analytics event

---

src/proto/api_messages-test.js
src/proto/api_messages.js
test/e2e/tests/buyflow.js

Adding events created in cl/476087048

Add new events for tracking errors

---

src/runtime/audience-action-flow-test.js
src/runtime/audience-action-flow.js
test/e2e/tests/buyflow.js

Survey iframe creation: cl/468501615

Add iframe path for survey.

---

src/proto/api_messages-test.js
src/proto/api_messages.js

Copy paste of generated code and test changes for the api_messages proto.
Adds sharingPolicyEnabled for TwG to determine which sharing policies to set.

Update api_messages.js with generated changes to SkuSelectedResponse

---

src/utils/date-utils-test.js
src/utils/date-utils.js

Fix a bug when converts microseconds to seconds.

date-utils bug fix

---

src/utils/url.js

This PR removes an uncovered line by always setting a default origin

Improves coverage by always setting default origin

---

src/ui/activity-iframe-view-test.js

This PR adds tests to improve coverage of the src/ui/activity-iframe-view.js script

Improve coverage for src/ui/activity-iframe-view.js

---

src/runtime/auto-prompt-manager-test.js

Fix gtag and ga test setup

---

src/runtime/auto-prompt-manager-test.js

Refactor auto-manager-test.js util function for readability

---

shortcuts.sh

This PR updates the AMP build script to print an error message and return 1 when it detects local changes

AMP release: Improve error messaging

---

src/runtime/subscription-linking-flow-test.js
src/runtime/subscription-linking-flow.js

[SL] Throw an error if ppid is missing from request

---

demos/public/link-subscription.html

Add page for testing linkSubscription

---

src/runtime/runtime-test.js
src/runtime/runtime.js

Remove google fonts preconnect

---

demos/public/demos.js
demos/public/prod/subscriptions/link-subscription.html
demos/public/qual/contributions/link-subscription.html
demos/public/qual/subscriptions/link-subscription.html

Add different versions of the link-subscription test page for different environments. The pages need a different publisher ID depending on the environment.
b/258726652

Create prod/qual/contribution/subscription link-subscription pages

---

src/api/entitlements.js

Fix a issue that cause converting Timestamp failed in minified swgjs.

Fix a minified swgjs issue

---

src/utils/log-test.js

- Removes unecessary check that included an uncovered line
- Re-enables eslint

Improve coverage in log-test.js

---

src/utils/style-test.js
src/utils/style.js

- Adds tests
- Removes unused method

Improve coverage in style.js

---

src/runtime/basic-runtime-test.js

- Adds test for delegation of `linkSubscription()`

Improve coverage in basic-runtime.js

---

src/runtime/deferred-account-flow-test.js
src/runtime/deferred-account-flow.js

- Removes extra import
- Uses optional chaining (`?.`) instead of logical AND `&&`
- Creating a dummy function by binding `Promise.resolve()`, instead of creating an empty method that never runs and causes a missed line of coverage

Improve coverage in deferred-account-flow.js

---

src/runtime/experiments-test.js

Improve coverage in experiments-test.js

---

src/utils/gaa-test.js

- Simplifies fakes that never execute

Improve coverage in gaa-test.js

---

src/runtime/runtime-test.js

- Add test for sending publisher provided IDs

Improve coverage in runtime.js

---

src/runtime/callbacks-test.js

- Adds tests for warning messages

Improve coverage in callbacks.js

---

src/utils/style-test.js

- Updates style test so it specifically verifies this codepath: https://github.com/subscriptions-project/swg-js/blob/493befa7a54f46ab4800831007040c98b285274f/src/utils/style.js#L268

Fixes style test

---

src/runtime/extended-access/gaa-metering-regwall-test.js

- Cleans up SIWG buttons after tests
- Adds comments

Reducing flakiness of "renders Google Sign-In button" test

---

src/runtime/subscription-linking-flow-test.js
src/runtime/subscription-linking-flow.js

- Change desktop placement to bottom instead of center
- Do not show grey overlay
b/263416009
b/263415798

[SL] Update Subscription Linking dialog presentation

---

test/e2e/nightwatch.conf.js

- Allow 1m to connect
- Allow 3 retries

Give ChromeDriver more time to connect

---

src/utils/log.js

Improve coverage in log.js

---

package.json
test/e2e/globals.js
test/e2e/nightwatch.conf.js

- Removes unused code
- Inlines a few values
- Tells WebDriver to keep HTTP connections alive (for a default 3s duration)

Cleanup Nightwatch configuration

---

src/stories/AutoPrompt.stories.js
src/stories/ContributeButton.stories.js

https://screencast.googleplex.com/cast/NTI0MDU4NDIxOTM5NDA0OHxiNmFjYTU4Ny1mMw
Also making autoprompt & contribution button into template and use Args to write different stories like described here: https://storybook.js.org/docs/html/writing-stories/args#args-composition

Add subscription autoprompt to storybook demo

---

src/stories/AutoPrompt.stories.js
src/stories/ContributeButton.stories.js

- Removes a couple `eslint` comments that #2674 removed the need for

Remove extra `eslint` comments

---

src/runtime/extended-access/gaa-metering-test.js

- Adds two tests verifying callbacks are set.

Improve coverage in gaa-metering.js

---

src/model/page-config-resolver-test.js
src/model/page-config-resolver.js

- Adds five new tests
- Removes unreachable code
- Simplifies code where possible
- Fixes typo in existing test name

Improve coverage in page-config-resolver.js

---

src/runtime/services-test.js

Improve coverage in services.js

---

demos/index.js
demos/public/link-subscription.html
demos/public/prod/subscriptions/link-subscription.html
demos/public/qual/contributions/link-subscription.html
demos/public/qual/subscriptions/link-subscription.html
demos/public/subscription-linking.js

[SL] Update demos to use swg.js instead of swg-basic.js

---

src/runtime/propensity-server-test.js

Improve coverage in propensity-server.js (p2)

---

src/runtime/login-prompt-api-test.js

Improve coverage in login-prompt-api-test.js

---

src/runtime/entitlements-manager-test.js

- Adds two tests
- Adds an expectation to an existing test

Improve coverage of entitlements-manager.js

---

src/runtime/extended-access/html-templates.js
src/ui/ui-css.js

- Improves Extended Access CSS 
- Adds syntax highlight
- Removes an extra `!important` statement (which VS Code flagged, after adding the syntax highlighting)
- Formatting (which VS Code automatically applied, after adding the syntax highlighting)
- Fixes a typo in ui-css.js file

Improve Extended Access CSS with syntax highlighting

---

src/runtime/contributions-flow-test.js

- Adds a test
- Expands a test

Improve coverage in contributions-flow.js

---

src/runtime/extended-access/gaa-metering-regwall-test.js
src/runtime/extended-access/html-templates.js

Works with the es6-string-html VS Code extension.

Add syntax highlighting/formatting for HTML strings

---

src/runtime/meter-toast-api-test.js

Improve coverage for meter-toast-api.js

---

src/runtime/pay-client-test.js

- Adds three tests
- Combines two existing tests

Improve coverage in pay-client.js

---

src/runtime/extended-access/gaa-metering-test.js
src/runtime/extended-access/gaa-metering.js

Address https://github.com/subscriptions-project/swg-js/issues/2729

Make unlockArticle optional when showcaseEntitlement is provided

---

test/e2e/globals.js

- Waits 60s instead of 30s for E2E test conditions to be true

Wait 60s for E2E tests

---

build-system/tasks/internal-version.js

- Removes unused `subversion` CLI param

Remove unused CLI param (`subversion`)

---

vite.config.js

- Adds terminating newline to sourcemaps

Release: Add newline to sourcemaps

---

src/runtime/audience-action-flow-test.js
src/runtime/basic-runtime-test.js
src/runtime/button-api-test.js
src/runtime/contributions-flow-test.js
src/runtime/deferred-account-flow-test.js
src/runtime/link-accounts-flow-test.js
src/runtime/login-notification-api-test.js
src/runtime/login-prompt-api-test.js
src/runtime/meter-toast-api-test.js
src/runtime/offers-flow-test.js
src/runtime/pay-flow-test.js
src/runtime/services-test.js
src/runtime/services.js
src/runtime/subscription-linking-flow-test.js
src/runtime/wait-for-subscription-lookup-api-test.js

- Removes unnecessary "_/" from iframe URLs. This used to be necessary, but now it just causes a redirect, which slows down UX.

Optimization: Avoid unnecessary iframe redirects

---

build-system/tasks/unit.js
package-lock.json
package.json

- Upgrades `glob` npm package
- Updates how we import the `glob` package, to handle a breaking API change

Upgrade `glob` npm package

---

src/utils/errors.ts

Migrate src/utils/errors to TypeScript

---

src/model/client-config.js
src/runtime/client-config-manager-test.js
src/runtime/client-config-manager.js
src/runtime/link-accounts-flow-test.js
src/runtime/link-accounts-flow.js
src/runtime/services-test.js
src/runtime/services.js

Remove obsolete client config flag usePrefixedHostPath

---

src/model/client-config.js
src/runtime/client-config-manager-test.js
src/runtime/client-config-manager.js
src/runtime/link-accounts-flow-test.js
src/runtime/link-accounts-flow.js
src/runtime/services-test.js
src/runtime/services.js

Cherry-pick PR #2798 to amp branch.
b/271472443

[AMP] Remove obsolete client config flag usePrefixedHostPath

---

build-system/tasks/check-rules.js
src/model/doc.ts
src/runtime/experiment-flags.ts
src/runtime/experiments-test.js
src/runtime/experiments.ts
src/runtime/jserror.ts
src/runtime/services.ts
src/runtime/storage.ts
src/utils/date-utils.ts
src/utils/preconnect.ts
src/utils/url-test.js
src/utils/url.ts

- Migrate files to TypeScript
- Improve typing in `src/model/doc`
- Update rules

Migrate 3 utils and 5 runtime file to TypeScript

---

docs/CODEOWNERS

Add @oyj9109 to CODEOWNERS

---

src/runtime/audience-activity-listener.ts

cl/515646876 for reference of survey events.

Add survey events to audience activities allowlist

---

examples/sample-pub/sample-pub-app.js
examples/sample-pub/views/setup.html

Update Scenic demo to use qual script instead of tt

---

src/runtime/experiment-flags.ts
src/runtime/pay-client-test.js
src/runtime/pay-client.js

The flag has been fully launched since April 2021.

Clean up experiment flag pay-client-redirect

---

src/runtime/analytics-service-test.js
src/runtime/analytics-service.ts
src/runtime/experiment-flags.ts

The flag has been fully launched since April 2020.

Clean up flag update-google-transaction-id

---

src/runtime/experiment-flags.ts
src/runtime/runtime-test.js
src/runtime/runtime.js

The flag has been fully launched since April 2020.

Clean up references to smartbox experiment flag

---

src/runtime/services.ts

Fix cache keys in operating modes

---

src/api/subscriptions.ts
src/runtime/pay-flow-test.js
src/runtime/pay-flow.ts

Remove virtual gift logic

---

src/runtime/basic-runtime-test.js
src/runtime/runtime-test.js

Remove extra tests

---

src/components/activities-test.js
src/proto/api_messages-test.js
src/proto/api_messages.ts
src/runtime/analytics-service-test.js
src/runtime/analytics-service.ts
src/runtime/basic-runtime-test.js
src/runtime/basic-runtime.ts
src/runtime/deps.ts
src/runtime/entitlements-manager-test.js
src/runtime/runtime.ts
src/utils/date-utils.ts
src/utils/url-test.js
test/mock-deps.ts

Populates the navigation timing fields: runtime creation and load event start delay

Populate navigation timing

---

src/runtime/experiment-flags.ts
src/runtime/runtime-test.js
src/runtime/runtime.ts

This rollout is finalized. b/279620588.

Remove references to use_article_endpoint_classic flag

---

src/runtime/runtime-test.js
src/runtime/runtime.ts

Adds generation of log event EVENT_START_API, EVENT_SHOW_OFFERS_API and EVENT_SHOW_CONTRIBUTION_OPTIONS_API.

Log events

---

src/runtime/runtime.ts

Removes logRuntimeReadyEvent

---

src/runtime/runtime.ts

Add documentation for configured_ method in runtime.ts

---

src/runtime/runtime-test.js
src/runtime/runtime.ts

Log error when init is called after configuration

---

src/runtime/jserror-test.js
src/runtime/jserror.ts

Update jserror path to use /swg prefix

---

src/runtime/contributions-flow.ts

Remove extra code in `contributions-flow.ts`

---

renovate.json

Disable renovate

---

demos/public/qual/contributions/autoprompt-free.html
demos/public/qual/contributions/autoprompt-large-free.html
demos/public/qual/contributions/autoprompt-paywalled.html
demos/public/qual/contributions/button-dark.html
demos/public/qual/contributions/button-french.html
demos/public/qual/contributions/button-light.html
demos/public/qual/contributions/free-article.html

Update publication ID used in qual contribution demos

---

renovate.json

This reverts commit 58c67765ba6b570f539326c1ea0b46f063286700.
b/297030387

Revert "Disable renovate"

---

demos/public/qual/subscriptions/autoprompt-free.html
demos/public/qual/subscriptions/autoprompt-large-free.html
demos/public/qual/subscriptions/autoprompt-paywalled.html
demos/public/qual/subscriptions/button-dark.html
demos/public/qual/subscriptions/button-french.html
demos/public/qual/subscriptions/button-light.html
demos/public/qual/subscriptions/free-article.html

Update pub ID for qual subscription demos

---

vite.config.js

Add trailing newline to binary output

---

src/runtime/pay-client-test.js
src/runtime/pay-client.ts

Disables android native buyflow to mitigate b/298029927

Disable Android Native buyflow 

---

src/runtime/pay-client-test.js
src/runtime/pay-client.ts

disableNgbf

---

src/runtime/basic-runtime-test.js
src/runtime/basic-runtime.ts
src/runtime/experiment-flags.ts
src/runtime/runtime-test.js
src/runtime/runtime.ts
test/e2e/nightwatch.conf.js

This reverts commit d0b8f91d857e4f2b5ccfa2f2c88495e4038e668e.

Revert "Remove references to populate-client-config-classic flag"

---

third_party/gpay/src/payments_web_activity_delegate.js

Add `swg` URL param to Pay URLs

---

src/runtime/pay-client-test.js
src/runtime/pay-client.ts
test/_init_tests.js

These requests only generate errors.
b/301090147

Remove prefetch request for Pay URL

---

src/api/entitlements.ts
src/runtime/api-test.js
src/runtime/entitlements-manager-test.js

Make the user_id in entitlements available if present. Inclusion of the data is guarded by a server experiment flag.
b/273380742

Read user_id from entitlements data

---

src/runtime/audience-action-local-flow.ts
src/runtime/audience-action-local-flows-test.js
src/runtime/basic-runtime-test.js
src/runtime/basic-runtime.ts

We weren't handling the response to the sign in request properly. We remove our handler and put our logic into the original handler.

Make Rewarded Ads handle sign in properly.

---

src/runtime/event-type-mapping-test.js
src/runtime/event-type-mapping.ts

Similar to https://github.com/subscriptions-project/swg-js/pull/2280, we need to record the impression & sign up events for Google Analytics.

Add GA events for newsletter sign up

---

src/runtime/audience-action-local-ui.ts

Before:
https://github.com/subscriptions-project/swg-js/assets/106177651/a8273e3a-70ac-46c7-8e69-dd60c16ff198
After:
https://github.com/subscriptions-project/swg-js/assets/106177651/596da542-135c-49da-8604-c9ffb29d2703

Update rewarded ads thanks prompt css to better match mock

---

demos/public/qual/contributions/autoprompt-paywalled.html
src/runtime/audience-action-local-flow.ts
src/runtime/audience-action-local-flows-test.js

Also added the functionality to close the prompt after the submission is successful.
https://screencast.googleplex.com/cast/NjE3MjU5NDAyNDc0MjkxMnw4YTM5NzYwMi03Nw
The width of the prompt is set within the code snippet, so we can only set the overflow to scroll, but not able the make the prompt fit to screen if it's bigger than the screen

Put newlstter publisher prompt in the right position

---

src/runtime/basic-runtime-test.js
src/runtime/experiment-flags.ts
src/runtime/runtime-test.js
src/runtime/runtime.ts
test/e2e/nightwatch.conf.js

Remove references to flag `populate-client-config-classic`

---

src/runtime/audience-action-local-ui.ts

Adjusting spacing and scaling in the UI. Waiting on a11y and UX approval for the changes before pushing.
b/304360857

Adjust spacing on rewarded ads

---

examples/sample-pub/sample-pub-app.js
examples/sample-pub/views/article.html

Add suport for /config routes in the local scenic demo. This mirrors the functionality of deployed scenic.
New E2E tests for RRM:E will use these URLs in order to configure the appropriate publication IDs.
b/294265975

Support specifying config in URL in local scenic

---

src/runtime/audience-action-local-flow.ts
src/runtime/audience-action-local-flows-test.js

b/305016712, verified in local demo.

change codeSnippet field to rawCodeSnippet

---

src/i18n/swg-strings.ts

Want to make sure we can launch with our Brazilian alpha partner soon, but TC translations are taking longer than I thought.
Used bard to triple check the translation and it seems to be good.

Add tmp VIEW_AN_AD message for pt-br

---

src/runtime/audience-action-local-ui.ts

b/309676238
https://screencast.googleplex.com/cast/NjU1NzQwNDQ3MTc1NDc1Mnw0ZTIyNmI1Yy05Zg

add forced-color style for byop close button

---

src/model/auto-prompt-config.ts
src/model/client-config.ts
src/runtime/auto-prompt-manager-test.js
src/runtime/auto-prompt-manager.ts
src/runtime/client-config-manager.ts

Uses anyPromptFrequencyCap as default if prompt frequency cap is undefined.

[BETA Phase] Implements per prompt PromptFrequencyCap

---

src/runtime/auto-prompt-manager-test.js
src/runtime/auto-prompt-manager.ts
src/runtime/storage.ts
src/utils/constants.ts

b/325512188
https://docs.google.com/document/d/1H99mlR47aZZv_ZsCRkI6Iv_WUcpwaoeGgCExWSkdYCI/edit?resourcekey=0-9djhO0eRtzh5bMMrZ1dtBg&tab=t.0#heading=h.8ztm2we0184l

Prompt frequency by completions and dismissals, Global frequency by impressions.

---

src/runtime/auto-prompt-manager-test.js
src/runtime/auto-prompt-manager.ts

Adressing comments in https://github.com/subscriptions-project/swg-js/pull/3453.

Refactor Local Storage Timestamps type for frequency capping.

---

src/runtime/audience-action-local-flow-test.js
src/runtime/audience-action-local-flow.ts

Make background unclickable for client side interventions

---

src/runtime/audience-action-local-flow-test.js
src/runtime/audience-action-local-flow.ts
src/runtime/experiment-flags.ts

Remove old rewarded ad experiment code

---

src/runtime/audience-activity-listener-test.js
src/runtime/basic-runtime-test.js
src/runtime/basic-runtime.ts
src/runtime/experiment-flags.ts

Cleans up Logging Audience Activity experiment 

---

test/e2e/tests/basic.js
test/e2e/tests/basicSubscription.js
test/e2e/tests/buyflow.js
test/e2e/tests/contribution.js
test/e2e/tests/enterpriseSubscription.js
test/e2e/tests/manualInitialization.js
test/e2e/tests/smartButton.js

Disabled in https://github.com/subscriptions-project/swg-js/pull/3466. Test app and offers restored, re-enabling e2e tests.

Re-enable e2e tests

---

src/runtime/audience-action-local-flow.ts

Requested by PM to make debugging issues easier for publishers
b/328640462

Add no ad filled console warning

---

src/api/available-intervention-test.js
src/api/available-intervention.ts
src/api/intervention-type.ts
src/api/subscriptions.ts
src/runtime/audience-action-flow.ts
src/runtime/auto-prompt-manager.ts
src/runtime/entitlements-manager-test.js
src/runtime/entitlements-manager.ts
src/runtime/intervention.ts
src/runtime/runtime.ts

Split intervention types to avoid circular dependency

---

src/runtime/runtime-test.js
src/runtime/runtime.ts

Tested locally with `<html lang="fr-FR">` and `<html lang="fr">`.
b/345212480

Set prompt language from element lang

---

demos/public/qual/contributions/autoprompt-paywalled.html
src/runtime/audience-action-local-flow-test.js
src/runtime/audience-action-local-flow.ts
src/runtime/auto-prompt-manager-test.js
src/runtime/auto-prompt-manager.ts

previewEnabled param was added in cl/642632853.
Screenshot: https://screenshot.googleplex.com/Ev8kcDQGxFos7sX
Tested locally when config id is in the url: https://screencast.googleplex.com/cast/NDc1MzQzMTEwODUxNzg4OHw2YWVjYTk4Mi03ZQ.

Render onsite preview for Rewarded ad and Newsletter BYOP

---

src/api/available-intervention.ts
src/runtime/entitlements-manager-test.js
src/runtime/entitlements-manager.ts

Filter interventions not enabled and enable surveys for enterprise api

---

demos/public/prod/enterprise/enterprise-funnel.html
src/runtime/audience-action-local-ui.ts

Update the width on small screens to take up 100% even if the content is small.
b/353509279
Before: https://github.com/user-attachments/assets/f7a27e1c-b6e7-4e51-ab48-14a6603d077b
After: https://github.com/user-attachments/assets/33f2d019-0581-4389-960e-2c5b42f10228

Update rewarded ad narrow screen width

---

demos/public/prod/enterprise/enterprise-funnel.html
src/api/available-intervention.ts

Noticed that some comments were missing and made some updates to the enterprise test site to support rewarded ads.
b/329307981

Update rewarded ad result comment and enterprise test site

---

src/runtime/audience-action-local-flow.ts

Fix small logical error

---

package-lock.json
package.json
test/e2e/pages/enterpriseContribution.js
test/e2e/tests/enterpriseContribution.js

Out of date version causing failing e2e tests.

Update chromedriver version

---

src/runtime/audience-activity-listener.ts

cl/687005543 for adding it in the proto

Add byo cta event to audience activities allowlist

---

src/runtime/event-type-mapping.ts

Add GA event for BYO CTA

---

package-lock.json
package.json
test/e2e/pages/basicSubscription.js
test/e2e/pages/enterpriseSubscription.js
third_party/gpay/src/payments_web_activity_delegate.js

Also updates chrome driver version + assertions to match updated iframes.

Add swgVersion URL param to Pay URLs

---

src/runtime/intervention.ts

Feature request from gTech to simplify onboarindg.
b/381949663

Add publisher provided name to Intervention definition

---

docs/CODEOWNERS

removes yeongjin as codeowner :(

Updates codeowners

---

src/runtime/experiment-flags.ts

add experiment flag for inline CTA

---

src/proto/api_messages-test.js
src/proto/api_messages.ts

b/394900839 - Update API messages to support closing iframe on gray pane click.

Add new close request

---

src/components/dialog-test.js
src/components/dialog.ts

Close iframe on gray pane click

---

src/runtime/audience-action-flow-test.js
src/runtime/audience-action-flow.ts

Allow audience actions to be completed from AudienceActionFlow

---

src/runtime/auto-prompt-manager-test.js
src/runtime/auto-prompt-manager.ts

Add googletag check for action eligibility

---

src/runtime/inline-cta-api-test.js
src/runtime/inline-cta-api.ts
src/runtime/offers-flow.ts
src/utils/cta-utils-test.js
src/utils/cta-utils.ts

tested locally: https://screencast.googleplex.com/cast/NDY5OTQ2MzQ5ODA3MjA2NHxlOWYyZDc2Zi0yMw

handle offer selection for inline subscription cta

---

src/runtime/analytics-service-test.js
src/runtime/analytics-service.ts
src/utils/cta-utils-test.js
src/utils/cta-utils.ts

b/424789518, inline CTA should have the context label added when logging.
https://docs.google.com/document/d/1EDSXZvy6Diuh0VmcehFVtzSDVrIYlz3UUkMx1N-2ltY/edit?tab=t.0#heading=h.koi45p38dalp

Add inline CTA context for action logging

---

src/runtime/contributions-flow.ts
src/runtime/inline-cta-api-test.js
src/runtime/inline-cta-api.ts
src/runtime/pay-flow-test.js
src/runtime/pay-flow.ts
src/utils/cta-utils-test.js
src/utils/cta-utils.ts

Right now the pay confirmation iframe would render in an dialog, we need to render it where the pay iframe is.
b/418814334 and b/424789518

render pay confirmation iframe inline where the code snippet is

---

src/utils/cta-utils-test.js
src/utils/cta-utils.ts

Similar to https://github.com/subscriptions-project/swg-js/pull/3771

Add inline cta label for contribution flow logging

---

demos/public/autoprompt-paywalled.html
src/runtime/basic-runtime.ts
src/runtime/inline-cta-api.ts

Going to add console log for inline cta to try to figure out a fix for b/431183634

Add console log for inline CTA

---

src/runtime/inline-cta-api-test.js
src/runtime/inline-cta-api.ts
src/runtime/pay-flow.ts

Adding removal of potential curly quotes and single quotes for inline 

---

src/runtime/audience-action-flow.ts
src/runtime/inline-cta-api.ts
src/utils/survey-utils-test.js
src/utils/survey-utils.ts

Only log for inline cta now.
Will use this as a test to see if the new event param is working.
b/431828886

Log inline CTA event params for Survey data transfer event

---

src/api/client-event-manager-api.ts
src/runtime/google-analytics-event-listener-test.js
src/runtime/google-analytics-event-listener.ts

This way publishers would be able to view inline cta event through Google analytics

Add cta mode to google analytics

---

src/proto/api_messages-test.js
src/proto/api_messages.ts

rebase api_messages
