subscriptions-project/swg-js

- src/components/dialog-test.js
- src/components/dialog.css
- src/components/dialog.js
- src/ui/toast.js
- src/utils/style-test.js
- src/utils/style.js
This is to support MS edge browser, since important styles would not be updated.
> Remove media query styles to be set as important

- docs/deferred-account-flow.md
- docs/flows.md
- src/api/subscriptions.js
Removed "not launched" in deferred account creation flow docs.
@ratana
> Removed "not launched" in deferred account creation flow docs

- src/runtime/pay-flow.js
As of today this should help a lot with getting things up and running quicker.
The change does add a maintainability burden, so it should be considered whether this is worth it, or if a more sustainable strategy is feasible.
> Add additional URLs to prefetch and preconnect.

- src/components/dialog.css
- src/ui/toast.js
- Use `transition` api for Toast animation.
- Animate Toast in 400ms.
- On close, animate toast again before removing the element from DOM
> Toast animation, use transition api

- src/components/dialog.js
- src/runtime/runtime.js
- src/ui/loading-view-test.js
- src/utils/dom-test.js
- src/utils/dom.js
Make CSS injection use `Doc.getHead()` and `Doc.getDocumentRoot()` to correctly handle AMP document mode when in shadow dom mode (IE inject the CSS inside the shadow root if needed).
> Make CSS injection use Doc to correctly handle shadow dom case.

- src/main.js
- src/model/page-config-resolver.js
- src/runtime/runtime.js
- src/utils/log-test.js
- src/utils/log.js
Adds a `debugLog()` utility function that is a gated by a `location.hash` value containing `swg.dbg=1`. Messages look like:
`[Subscriptions] message text`
Adds a `debugLog(config)` and `debugLog(mode)` to dump the config and mode on startup.
Fixes b/122649408
> Add debugLog()

- src/api/subscribe-response.js
- src/runtime/api-test.js
- src/runtime/deferred-account-flow.js
- src/runtime/pay-flow-test.js
- src/runtime/pay-flow.js
Store and pass`product_type` in the `subscriptionResponse` for `payconfirmiframe` to use.
This allows changes to the payconfirmiframe page to render the different text/label.
> Contributions: preserving  product_type

- src/api/propensity-api.js
- src/runtime/propensity-test.js
- src/runtime/propensity.js
- src/runtime/runtime-test.js
- src/runtime/runtime.js
- sendEvent() API now requires a PropensityEvent type as documented
- getPropensityModule() now provides the Propensity Module without experiment enabled
- getPropensity() API is now hidden behind an experiment.
> Propensity API update and experiment changes

- build-system/eslint-rules/no-export-side-effect.js
Merges in a PR from `amphtml` that allows the ExportSpecifier https://github.com/ampproject/amphtml/pull/22913
This will allow for cleaner re-exporting of symbols.
Example:
```js
export {obj as deprecatedObj} from 'lib';
```
Instead of:
```js
import {obj} from 'lib';
export const deprecatedObj = obj;
```
> ♻️ ESLint Rules: Allow ExportSpecifier

- exports/swg.js
AMP needs to create a new ClientEventManager and cannot just rely on the API
> export event manager

- src/runtime/client-event-manager-test.js
- src/runtime/client-event-manager.js
The primary purpose was to log errors thrown by event listeners or filterers to the console to ensure they aren't just lost.
While I was doing that, I improved the organization of the event manager tests because my test code writing skills have improved since I created these and I was adding new tests to verify the logging behavior anyway.
> Event Manager / Improve Error Handling

- src/runtime/jserror-test.js
Updates JSError test expectations to match the shared behavior of Chrome and Firefox. When creating new Errors, the two browsers differ in terms of:
- Line number being defined
- Content of traces
> Fixes JSError tests for FF

- src/runtime/button-api-test.js
- src/runtime/button-api.js
- src/runtime/pay-flow-test.js
- src/runtime/pay-flow.js
- src/runtime/runtime-test.js
- src/runtime/runtime.js
Replaces ACTION_SUBSCRIBE logging with ACTION_PAYMENT_FLOW_STARTED in pay-flow.js. Adds EventManager as a private member to Runtime and uses that in ButtonApi to log SwG button click events.
> Log SwG button clicks with EventManager

- src/runtime/button-api-test.js
- src/runtime/button-api.js
- src/runtime/runtime-test.js
Adds impression logging to ButtonApi on attach of SwG button. Adds tests to verify that impression logging is being done.
Note that we decided to add impression logging on our end as well as have publishers log button impression with LoggerApi because we will then be able to grab all impressions done on the SwG button and differentiate between publisher logged impressions and SwG logged impressions by looking at the event origin.
> SwG Button Impression Logging

- src/runtime/entitlements-manager-test.js
- src/runtime/entitlements-manager.js
Removes the IMPRESSION_PAYWALL logging in getEntitlements call as it is incorrectly placed and non-informative.
> Remove IMPRESSION_PAYWALL logging from getEntitlements.

- src/runtime/analytics-service-test.js
- src/runtime/analytics-service.js
- src/runtime/client-event-manager-test.js
- src/runtime/client-event-manager.js
Updates analytics service to be aware of PUBLISHER_CLIENT when attempting to ignore publisher logged events.
Also adds some unit tests for the new logSwgEvent helper function.
> Event Manager / Analytics Service / Respect Publisher Events

- src/runtime/analytics-service-test.js
- src/runtime/analytics-service.js
- src/runtime/runtime-test.js
- src/runtime/runtime.js
Does some final cleanup to remove the old logging function from analytics service.  Everything should now use event manager.
> remove logEvent from analytics service

- .eslintrc
> Updated lint rule: using console.* would trigger warnings

- src/runtime/analytics-service-test.js
- src/runtime/analytics-service.js
The subscription state change event was not intended to be part of our analytics service.  The client code should avoid sending the event back to the analytics service.
> Analytics ignores subscription state change (for now)

- src/utils/string-test.js
- src/utils/string.js
Ensure that two UUIDs generated on different devices can only collide if they were generated at the same MS of the month.
> Tie UUID to time

- src/components/dialog.js
This PR fixes a bug where the Dialog wasn't waiting for its iframe to finish loading before adding content to it. The bug only affected Firefox (https://bugzilla.mozilla.org/show_bug.cgi?id=1493878).
> 🐛 Fixes Dialog iframe issue in FF

- src/components/dialog-test.js
This PR fixes a flaky dialog test that was consistently failing for me locally due to a subpixel difference.
Before it was failing locally due to a `0.0045` pixel difference:
Now it passes locally :smile:
> Fixes a flaky dialog test

- src/runtime/services.js
This PR adds a hash param (`swg.boqjsmode`) that can be used to trigger full optimization of JS in Boq web iframes.
This will make it easier to test how compiled Boq JS interacts with OSS SwG code when developing locally.
> 🏗 Adds hash param for testing optimized Boq JS

- src/components/dialog-test.js
- src/components/dialog.js
This PR disables FixedLayer, but leaves an easy way to enabled it via Chrome's local overrides for testing.
> 🐛 Disables fixed layer

- third_party/gpay/src/payjs_async.js
- third_party/gpay/version.txt
Regarding the bug that payment clearcut log missing SwG native buy flow events, payment team made another change to fix it. This PR is to sync our fork to their update-to-date pay_async.js.
> Sync SwG forked payjs_async to its origin

- src/api/subscriptions.js
- src/runtime/link-accounts-flow-test.js
- src/runtime/link-accounts-flow.js
- src/runtime/runtime-test.js
- src/runtime/runtime.js
Adds `ampReaderId` param to the `linkAccount`, and passes it to the Boq iframe if present
> ✨ Adds ampReaderId param to linkAccount fn

- src/runtime/wait-for-subscription-lookup-api-test.js
This PR updates tests in the `runtime/wait-for-subscription-lookup-api-test.js` to use async/await
> Updates a few tests to use async/await

- src/runtime/storage-test.js
- src/ui/activity-iframe-view-test.js
- src/ui/loading-view-test.js
- src/ui/toast-test.js
- src/utils/activity-utils-test.js
- src/utils/animation-test.js
- src/utils/bytes-test.js
- src/utils/document-ready-test.js
- src/utils/json-test.js
- src/utils/log-test.js
- src/utils/timer-test.js
- src/utils/xhr-test.js
- Finishes moving `expect` calls to top level in tests
- Fixes "toast-test.js" by using `getComputedStyle` fn
> ✅ Finishes moving `expect` calls to top level in tests

- .codecov.yml
The codecov/patch status only measures lines adjusted in the pull request or single commit, if the commit is not in a pull request. This status provides an indication on how well the pull request is tested.
> Disable codecov checks on patch for now

- src/runtime/pay-client-test.js
- src/runtime/pay-client.js
This fixes an issue where we tell the client to log something and then immediately tell the client to redirect.  This causes the page to redirect before the logging occurs (causing broken logs).
Ultimately we really need a "logging promise" that we can wait to resolve prior to redirecting the page but it will take some time to implement that.  As a temporary solution I am proposing a brief delay before a page redirect.
> Delay Redirect so Logging Can Finish

- src/runtime/pay-client-test.js
- src/runtime/pay-client.js
Reduces the redirect delay to improve user-experience while keeping one in place so logging should hopefully work as expected.
> Reduce Redirect Delay

- src/runtime/callbacks-test.js
- src/runtime/callbacks.js
- src/runtime/pay-flow.js
When the user closes the gPay window:
* Stop throwing the abort error
* Stop triggering payment response with null response data (it should just trigger cancel workflow)
> Stop throwing errors on window close

- src/runtime/contributions-flow.js
- src/runtime/offers-flow-test.js
- src/runtime/offers-flow.js
- src/runtime/pay-flow-test.js
- src/runtime/pay-flow.js
- src/runtime/runtime.js
- Force PayStartFlow to only accept a SubscriptionRequest
- Quote object keys to protect against minification mismatch.
- Move some logic out of constructor closer to where the values are
used.
> Simplify internal pay-flow interfaces.

- test/e2e/pages/login.js
This reduces E2E flakiness. The main change was adding `waitForElementNotPresent('@password')` to confirm the Google login completes ⏳
> ✅ E2E login: Wait for password element to go away

- src/runtime/client-event-manager.js
- src/runtime/pay-client-test.js
- src/runtime/pay-client.js
The analytics server logging promise is only ready after the event manager ready promise.  So first wait for the event manager promise, then get and wait for the logging promise.
> Respect event manager ready promise

- src/runtime/offers-flow-test.js
- src/runtime/offers-flow.js
This logging is already done on the server and is currently happening twice for every show offers list displayed.  The client doesn't know the offers shown so it can't happen on the client.
> Remove SHOW_OFFERS logging

- src/components/activities-test.js
- src/components/activities.js
- src/runtime/analytics-service-test.js
- src/runtime/offers-flow-test.js
Currently, when a boq iframe wants to log this request is sent directly to the SwG analytics server.  Events communicated in this manner will not get sent to Propensity.  In order to resolve this issue, the SwG client will listen for AnalyticsRequests messaged to it from inside the boq iframes.  It will then redirect those events to the event manager which can send them out to both SwG analytics and Propensity.
Old path:
boq iframe -> analytics service -> analytics server
New path:
boq iframe -> swg client -> event manager -> { analyticsServer, propensity }
This only allows the client to listen for these events and does not actually implement any logging of this nature.  That will come in future development.
> SwG Server to Client Side Logging

- src/runtime/analytics-service-test.js
- src/runtime/analytics-service.js
- src/runtime/experiment-flags.js
- src/runtime/pay-flow-test.js
- src/runtime/pay-flow.js
This makes the PayClient self reliant in determining if the user is returning from a popup or a redirect and removes code from the analytics client that was being used to make this determination.
> Ensure "WasRedirected" Calculation is Correct

- src/runtime/analytics-service-test.js
- src/runtime/analytics-service.js
- src/runtime/runtime-test.js
- src/runtime/runtime.js
The problems:
1) The core problem is that "openIframe" (called in analytics-service before it sets up context) relies on the analytics-service context.  
a) This means that some logs will be missing context information (such as client version).
2) The secondary problem is that one of the context properties (experiments) can change dynamically or might not all be set when analytics service is constructing at load.
This development:
1) Sets up context during load for all properties that can be set.
2) Waits a little longer to set experiments and does so before calling openIframe
3) Fixes them again once the port is ready.
3) Ensures runtime forwards experiment changes to analytics so it has the current state.
There is still a "hole" here in that openIframe may not have some experiment data …
> Resolve Issues with Analytics Context

- src/runtime/propensity-server-test.js
- src/runtime/propensity-server.js
In order to avoid double encoding some values, Propensity will eventually change their URL structure.  For now, this sends that data both ways.  Eventually the old method can be removed.
> send new parameter structure to propensity

- .eslintrc
- src/polyfills/array-includes-test.js
- src/polyfills/document-contains-test.js
- src/polyfills/domtokenlist-toggle-test.js
- src/polyfills/math-sign-test.js
- src/polyfills/object-assign-test.js
- src/runtime/client-event-manager-test.js
- src/runtime/runtime-test.js
- src/utils/document-ready-test.js
- src/utils/types-test.js
- src/utils/xhr-test.js
This PR migrates tests to use for/of instead of forEach. If the inner body of a for loop needs to use `await`, it just works with for/of. Whereas with forEach, the developer would have to add boilerplate like `await Promise.all(list.map(val => { /** testing val... */ }))`. Personally I find for/of leads to more readable tests as well.
> ✅ Migrates tests to use for/of

- src/runtime/pay-client.js
TODO: Check with real iOS device
Some iOS devices, possibly those with cookies disabled, are encountering the following error when `window.localStorage` is accessed 
[go/ampe/CNvNmqTktNvi3wE](go/ampe/CNvNmqTktNvi3wE)
```
Error: The operation is insecure.
at localStorage (https://raw.githubusercontent.com/ampproject/amphtml/2002192257490/third_party/subscriptions-project/swg.js:15125)
at createPair_ (https://raw.githubusercontent.com/ampproject/amphtml/2002192257490/third_party/subscriptions-project/swg.js:15097)
at getOrCreatePair_ (https://raw.githubusercontent.com/ampproject/amphtml/2002192257490/third_party/subscriptions-project/swg.js:15038)
at (https://raw.githubusercontent.com/ampproject/amphtml/2002192257490/third_party/subscriptions-project/swg.js:14843)
at …
```
> 🐛 Wraps localStorage check in try/catch

- src/model/page-config.js
- src/utils/error-logger-test.js
- src/utils/error-logger.js
Addresses https://github.com/subscriptions-project/swg-js/issues/1016
Introduces a logging convention similar to, and compatible with, ampproject/amphtml. Also updates one user error to use the error logger. The module is used like this:
```javascript
import {user, dev} from '../utils/error-logger';
user().expectedError('Illegal configuration option');
try {
doWebRequest();
} catch (e) {
dev().error(e);
}
```
> Introduce amphtml-style error logging conventions/helpers

- src/api/subscribe-response.js
- src/runtime/pay-flow-test.js
- src/runtime/pay-flow.js
Updated pay completion flow to forward information about whether a contribution was one-time or not to the payConfirmIframe. Added a test to check this new behavior, and modified old tests to accommodate for the new response.
> Pay complete flow now provides one-time status

- src/runtime/experiment-flags.js
- src/runtime/pay-client-test.js
- src/runtime/pay-client.js
- src/runtime/runtime-test.js
- src/runtime/runtime.js
-Inside of PayClient, moves PaymentsAscynClient initialization into start method instead of initialization upon PayClient ctor.
-Removes payments prefetch call from Runtime and puts it in PayClient.start().
-Fixes and Adds tests.
> ♻  Moves Payments Client Initialization into start() from ctor

- src/runtime/pay-client.js
Declares this.client_ once in pay-client.js to fix gulp errors by setting it as null and then checking for the lazy-load pay-client experiment.
> Update this.client_ instantiation in pay-client.js

- examples/sample-pub/publisher.js
- examples/sample-pub/styles.css
- Properly clear entitlements, to make sure new entitlements are fetched
- Places "Reset metering PPID" button above the Show Offers overlay, to prevent dead ends
> Improves Metering demo

- src/runtime/pay-client-test.js
- src/runtime/pay-client.js
- src/runtime/runtime-test.js
- src/runtime/runtime.js
Removes all pay client lazy load experiment code in swg.js since the experiment has been launched since late July without issues.
> Remove Pay Client Lazyload experiment

- examples/sample-pub/metering.js
- examples/sample-pub/publisher.js
- examples/sample-pub/styles.css
- examples/sample-pub/views/article.html
This PR adds the Regwall to the Metering Entitlements demo in `swg-js`. The PR adds a "Mock GSI completion" button to simulate the Regwall flow's completion. 
It's worth noting, updating the public Scenic demo will require more work since public Scenic has its own metering logic already which we'll need to extend
> Metering Entitlements demo: Adds Regwall

- examples/google-signin/google-signin-iframe.html
There is a missing parameter in the metering iframe example for the allowed origins of the SwG iframe. Adds in a list containing news.google.com since that is where the production iframe is hosted from.
> Sends list of allowed origins in example iframe.

- examples/sample-pub/demo.js
- examples/sample-pub/publisher.js
- src/runtime/entitlements-manager.js
- src/runtime/meter-toast-api-test.js
- src/runtime/meter-toast-api.js
Adds call to native subscribe callback function if the subscribe button is clicked on the metering toast iframe. Adds tests. Adds ability to test the flow in sample publisher.
> Adds handling of subscribe button on metering toast iframe

- build-system/tasks/compile.js
Changes the minified name used for the Google Sign In script to use a new argument to separate swg.js names with the GSI name.
> Change minified name for GSI JS.

- src/components/dialog-manager.js
- src/runtime/meter-toast-api.js
Adds drop shadow to meter toast iframe on mobile by performing a media query in meter-toast-api.js and adding an event listener for changes. The current 'box-shadow' isn't dark enough for the meter toast specifications. Also adds the ability to grab the dialog from DialogManager.
> Adds drop shadow to meter toast iframe on mobile

- src/utils/gaa-test.js
- src/utils/gaa.js
This PR specifies the GSI `select_account` prompt for the sign in flow
https://developers.google.com/identity/sign-in/web/reference#gapiauth2signinoptions
The 'select_account' prompt has better iOS support
> Regwall: Show the GSI select_account prompt

- src/runtime/entitlements-manager.js
- src/runtime/meter-toast-api-test.js
- src/runtime/meter-toast-api.js
This PR updates the Meter Toast to only call the `consume()` callback when a user dismisses the Meter Toast to consume a free read. Clicking the "Subscribe" button will no longer trigger the `consume()` callback
> Meter Toast: Only call consume() callback when necessary

- src/runtime/meter-toast-api-test.js
- src/runtime/meter-toast-api.js
Adds a warning that tells devs that they haven't called setOnNativeSubscribeRequest and therefore the "Subscribe" button will not show on the meter toast iframe.
> Add warning in meter toast API on missing subscription callback

- examples/sample-pub/publisher.js
- src/runtime/entitlements-manager.js
- src/runtime/meter-toast-api-test.js
- src/runtime/meter-toast-api.js
We now remove event listeners when calling close request and on "Subscribe" button tests. Adds tests to check these cases.
> Remove event listeners on different events in meter toast

- src/runtime/entitlements-manager-test.js
- src/runtime/entitlements-manager.js
Updates consume_ in EntitlementsManager so that we only show the meter toast if the field 'showToast' in the metering entitlement response's details is true or not provided. Adds tests to check the various cases.
> Don't show meter toast if 'showToast' is false

- src/runtime/meter-toast-api-test.js
- src/runtime/meter-toast-api.js
Currently, the meter toast iframe closes immediately on any scroll on desktop. Now, we will only close the iframe on desktop if the scroll distance is greater than 100.
> Don't close meter toast immediately on scroll.

- src/runtime/meter-toast-api-test.js
- src/runtime/meter-toast-api.js
Does a partial rollback of the timeout handling done in [this PR](https://github.com/subscriptions-project/swg-js/pull/1469), replacing the 10 second timeout on the dialog opening with a call to the onConsume callback on all cancellations. This protects us against the case of a user closing the dialog before it renders without the meter being decremented without using a timeout. Adds a boolean to protect against calling onConsume twice. Adds test.
> Replace timeout with cancellation catch in Meter Toast

- src/runtime/runtime-test.js
- src/runtime/runtime.js
- src/utils/gaa-test.js
- src/utils/gaa.js
This PR creates a new `queryStringHasFreshGaaParams` method from the ashes of the `urlContainsFreshGaaParams` method
Also refactors the `setShowcaseEntitlement` tests for readability
https://testing.googleblog.com/2019/12/testing-on-toilet-tests-too-dry-make.html
> Improves method for checking GAA params

- src/utils/gaa-test.js
- src/utils/gaa.js
Publishers will be able to disable scrolling on their own if they'd like to
> Showcase Regwall: Removes scroll disabling

- src/model/doc.js
- src/model/page-config-writer.js
And update the page config writer to pass in the Document accessed via Window..
> Revert Doc's getRootNode return type change to Node

- src/utils/gaa-test.js
- src/utils/gaa.js
Fixes issue where the following error is thrown on a site that sets a `languageCode` to a value that doesn't exist in our I18N map (e.g. `"es"`)
```
gaa.js:402 Uncaught (in promise) TypeError: Cannot set property 'innerHTML' of null
at Function.Y.Dd (gaa.js:402)
at Function.Y.show (gaa.js:334)
```
> Use `msg` for translations

- src/utils/gaa-test.js
- src/utils/gaa.js
This PR makes the Showcase Regwall go away and reject its promise if the Google Sign-In button fails during its setup
> Showcase Regwall: Handle GSI failures

- .github/workflows/ci.yaml
This PR adds comments explaining why we're using Ubuntu 20.04 LTS and Java 8 for our GitHub Actions
> CI: Adds comments regarding Java 8 and Ubuntu 20.04 LTS

- build-system/tasks/github.js
Based on advice in this document, verified using cURL
https://docs.github.com/en/rest/overview/other-authentication-methods#basic-authentication
> GitHub API: Send token via Authorization header

- src/runtime/entitlements-manager-test.js
- src/runtime/entitlements-manager.js
Switches from using regular base64 encoding (`btoa`) for the metering params in the getEntitlements request to Base64 URL encoding. Also encodes the string with UTF8 safe encodings to support non-Latin characters. Updates tests.
> Base64Url encode the metering params

- assets/swg-button.css
- src/i18n/swg-strings.js
- src/runtime/auto-prompt-manager.js
- src/runtime/basic-runtime.js
- src/runtime/button-api-test.js
- src/runtime/button-api.js
- src/runtime/client-config-manager.js
- src/runtime/mini-prompt-api.js
Also consolidates mini prompt and button strings, and updates the ClientConfigManager to use optional chaining when creating the ClientConfig object.
> Update button UX to split on revenue model. Only applies to swg-basic for now.

- build-system/check-package-manager.js
- build-system/tasks/compile.js
- contributing/DEVELOPING.md
- package.json
- Installs latest Nodejs dependencies automatically (except on CI systems since it'd be redundant)
- Removes need to manually install/update Yarn (uses `npx yarn` instead)
- Removes instructions to install Java 1.8
- Updates comments
> Simplifies setup

- build-system/tasks/compile.js
- gulpfile.js
#1552 started automatically updating dependencies, but it was still failing if a dependency was missing :joy: - this PR fixes that
> Gulp: Install dependencies before anything else

- build-system/tasks/assets.js
This PR updates the `gulp assets` command to compile the `swg-mini-prompt.css` file
> Compile swg-mini-promp CSS

- src/utils/style.js
This PR fixes an issue where the SwG UX iframes sometimes float above the bottom of the window. I noticed it on a popular WordPress theme, Twenty Seventeen. The theme sets a `margin-bottom` on all `iframe` elements
> Remove margin-bottom for SwG UX iframes

- src/runtime/basic-runtime-test.js
- src/runtime/basic-runtime.js
- src/runtime/google-analytics-event-listener.js
Starts listening to GA Events in ConfiguredBasicRuntime by constructing a GoogleAnalyticsEventListener and calling its start() method in ConfiguredBasicRuntime's ctor. Adds test to ensure it is instantiated correctly and listens to events.
> Start listening to GA Events in ConfiguredBasicRuntime

- src/runtime/pay-flow-test.js
- src/runtime/pay-flow.js
useUpdatedConfirmUi will enable the new thank you UI, which is set based on the client config's useUpdatedOfferFlows flag.
> Send useUpdatedConfirmUi argument as part of payconfirmiframe request.

- src/proto/api_messages-test.js
- src/proto/api_messages.js
- src/utils/url-test.js
Adds a subscription_flow string to EventParams that allows us to input the SubscriptionFlow enum value into analytics events. This makes it so we can differentiate between contributions and subscriptions flows and log events to Google Analytics different in either flow.
> Add subscription_flow string to EventParams.

- src/runtime/basic-runtime-test.js
- src/runtime/basic-runtime.js
- src/runtime/runtime-test.js
- src/runtime/runtime.js
Moves GA event listener to ConfiguredRuntime from the basic runtime because there are events logged within the ConfiguredRuntime constructor that the GA event listener needs to listen to.
> Move GA event listener to ConfiguredRuntime

- build-system/tasks/closure-compile.js
This PR should fix the sourcemaps error:
> Could not load content for https://news.google.com/swg/js/v1/dist/src/utils/log.js (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)
> Compiler: Fixes sourcemaps

- src/runtime/contributions-flow-test.js
- src/runtime/contributions-flow.js
Adds 'supportsEventManager' to contributions flow iframe request so that we can use Event Manager to log in the contributions iframe. This makes it so Google Analytics can listen to events that originated in the contributions iframe.
> Add 'supportsEventManager' to contributions flow iframe

- src/runtime/google-analytics-event-listener-test.js
- src/runtime/google-analytics-event-listener.js
Adds a call to getSubscriptionFlow() when getting the subscriptionFlow field in the additionalParams objects. Adding this call allows for additionalParams to be a JSON object or an EventParams class instance, which is necessary since this value isn't strongly typed: https://github.com/subscriptions-project/swg-js/blob/main/src/api/client-event-manager-api.js#L37
> Add call to getSubscriptionFlow in GA event listener

- src/runtime/entitlements-manager-test.js
- src/runtime/entitlements-manager.js
Here's the warning:
`SwG Entitlements: Please specify a metering state ID string, ideally a hash to avoid PII.`
> Showcase: Warn about invalid metering state IDs

- src/i18n/swg-strings.js
This PR adds a single whitespace between the alphabet and kana per Google style guide (https://support.google.com/styleguides/faq/6356307?hl=ja&rd=1)
> SwG Basic: Updates ja translation

- src/utils/string-test.js
- src/utils/string.js
This PR adds a new error message (`Swgjs only works on secure (HTTPS or localhost) pages.`). Hopefully this lets developers know that they should test Swgjs on either localhost or HTTPS pages
This PR also adds tests to improve coverage
> Logs error message when crypto API isn't available

- src/runtime/contributions-flow-test.js
- src/runtime/contributions-flow.js
- src/runtime/offers-flow.js
- Fixes a bug where Contribution flow dialogs were always closable, regardless of the `isClosable` param's value
- Adds a test to catch regressions
- Updates the code inside of the Subscription flow that chooses a default value for the `isClosable` param's value. This code wasn't broken, but it was easy to simplify, so why not
> Contributions: Allow for non-closable dialogs

- package.json
- yarn.lock
This PR installs Yarn locally in the Swgjs project. This will speedup commands starting with `npx yarn`, since `npx` will no longer have to download Yarn each time
> Installs Yarn locally for faster commands

- package.json
Swgjs only needs Yarn during development
> Move Yarn to dev dependencies

- build-system/tasks/changelog.js
This PR updates the changelog command to suggest a version number. Since the previous version is available, this PR just increments that version by 1
This makes the release easier, and will let us simplify our documentation a bit too
> Changelog: Suggest a version number

- shortcuts.sh
This command gives us a changelog for a Swgjs release. We can use the changelog as the release's description. The changelog also includes the next version number (ex: 0.1.22.123), which we will use in several places, like the "Release title" and "Version tag".
> Release: Add swgjs_changelog shortcut

- build-system/tasks/changelog.js
- build-system/tasks/github.js
- build-system/tasks/publish.js
- gulpfile.js
This adds a `publish` step to gulp, reusing the `changelog` command but providing the information necessary to fill in the blanks for a release. 
I added a `--draft` param to support test publishing drafts before publishing full releases if we'd like
> Added a publish build step

- src/runtime/experiment-flags.js
- src/ui/activity-iframe-view-test.js
- src/ui/activity-iframe-view.js
This PR creates an experiment that allows users with small screens to scroll down and see important stuff like the "Already a contributor?" button
> Allow scrolling within dialogs, hidden behind an experiment

- build-system/tasks/github.js
This PR logs the `body` JSON from the GitHub API's error responses. Before, just the HTTP status code was logging
> GitHub tasks: Logs error messages from GitHub API

- assets/swg-button.css
Styles adjusted to match Figma mocks
Before:
After:
(Note: the mock for the light icon uses Grey 800, this is using Grey 900 since 800 is not available. That value may change but nothing else should)
> fix(190965214): adjust styling to match mocks

- assets/swg-button.css
Design wants to use the lighter grey. The referenced SVG was using the default (900)
> fix: using the grey 700 image

- shortcuts.sh
This shortcut makes sure developers are on the freshest branch possible before generating a release
> Shortcuts: swgjs_publish

- src/api/entitlements-test.js
- src/api/entitlements.js
Tokens returned for dev mode are used for testing/development and should not be cached for use outside of the current session.
> Do not cache dev mode tokens locally

- src/components/dialog.css
This PR fixes overlapping breakpoints at 640px width
This PR also rewrites some comments
> Dialog/Toast CSS: Fixes overlapping breakpoints, and rewrites some comments

- assets/swg-mini-prompt.css
The current icon styles were written assuming a content-box box-sizing model, but 3p sites might have a style rule that sets box-sizing to border-box throughout the site (like Scenic does!).
Before:
After:
> Explicitly set box-sizing of miniprompt close icon to content-box.

- src/runtime/basic-runtime.js
This PR enables the `alwaysShow` parameter to be passed through from the init() function in swg-basic.js. To preserve existing init() snippets, the parameter defaults to `false` if not set, which is the current behavior.
No tests are included in this change, as the param's validity is already being tested.
> Enabled alwaysShow to use a passed param

- src/utils/gaa.js
The Regwall's title is keyboard focusable, but we don't want it to be outlined, even if sites add a custom outline style for focused elements
> Showcase: Disables outline CSS on Regwall's title

- docs/embed-client.md
- src/api/entitlements.js
- src/model/page-config-resolver-test.js
- src/model/page-config.js
- src/runtime/api-test.js
Allow wildcard product id - eg `subscriptions.init('example.com:*');`
Wildcard will unlock on any entitlement as long as the publication part matches.
Tracked internally as b/183608659
> Support wildcard product id on page

- assets/swg-button.css
- src/runtime/button-api.js
Now that elements like `<span>`s can be SwG buttons, the HTML/CSS needs to change a bit
> SwG Buttons: Fix disabled state for elements other than buttons

- src/components/dialog-manager-test.js
- src/components/dialog-manager.js
- src/components/dialog-test.js
- src/components/dialog.js
This allows setting the dialog height to be 100% of the viewport
height on smaller screens
> Allow setting maxAllowedHeightRatio for the dialog height

- src/proto/api_messages-test.js
- src/proto/api_messages.js
- src/runtime/analytics-service-test.js
- src/runtime/analytics-service.js
- src/utils/url-test.js
This PR adds a timestamp of the current client machine to every outgoing analytics request.
> Set client timestamp on outgoing analytics events

- src/runtime/entitlements-manager-test.js
- src/runtime/entitlements-manager.js
This PR removes some unused functionality* and clarifies some comments
* SwG's first-party iframes don't send Swgjs any Showcase entitlement events
> Showcase: Simplify entitlements logging

- src/components/dialog-test.js
- src/components/dialog.js
- Add new method to open the Dialog in the specified container
- Add iframeCssClass to DialogConfig to specify the iframe CSS class to use instead of swg-dialog
> Allow Dialog to be contained in a given element and iframe CSS class

- src/api/entitlements.js
- src/runtime/entitlements-manager-test.js
- src/runtime/entitlements-manager.js
Subscription unlock events from crawlers aren't worth logging, they just pollute logs
> Analytics: Avoid logging subscription unlock events for crawlers

- demos/public/qual/contributions/autoprompt-paywalled.html
This PR fixes a hardcoded a qual JS URL from #1899
> Demos: Load correct JS for qual autoprompt demo

- src/api/basic-subscriptions.js
- src/runtime/basic-runtime-test.js
- src/runtime/basic-runtime.js
- src/runtime/client-config-manager-test.js
- src/runtime/client-config-manager.js
- src/runtime/contributions-flow-test.js
- src/runtime/contributions-flow.js
- src/runtime/pay-flow-test.js
- src/runtime/pay-flow.js
When forceLangInIframes is enabled and lang is specified, the language will be propagated to override the default language selection behavior in the iframes. 
I also did a little bit of refactoring in pay-flow-test.js to use more shared test helper functions/variables.
> Add forceLangInIframes to ClientOptions and set it to true in basic-runtime.js

- src/components/dialog-test.js
- src/components/dialog.js
- src/ui/loading-view-test.js
- src/ui/loading-view.js
- src/ui/ui.css
Previously, the bottom corners weren't rounded, since it was assumed that the loading container would be a bottom sheet rather than a centered dialog.
Screenshot:
https://screenshot.googleplex.com/62dJ3bRrVdPoBH9
> Add rounded bottom corners to the desktop centered loading view

- src/utils/gaa.js
The `show` method can return several types of user objects now, depending on which sign in button a publisher uses. This PR updates the JS type comments to reflect that flexibility
http://b/200458496
> Showcase Regwall: Expand the `show` method's possible return types 

- src/utils/gaa.js
This PR fixes an issue where publisher CSS interferes with the "Already have an account?" link's text underline (b/202482741)
This PR also removes styles for a "no-thanks-button". I can't see anywhere that Swgjs renders that element
> Showcase: Underline link

- build-system/tasks/jsify-css.js
Fixes a break from the linter in our release process
Before:
After:
> chore: add EOL to CSS stylesheets

- .github/workflows/ci.yaml
Manual node install step is failing, but github documents using their own action which seems to work better.
> Update CI to use setup-node action

- src/runtime/callbacks-test.js
- src/runtime/callbacks.js
- src/runtime/pay-flow-test.js
- src/runtime/pay-flow.js
This allows attaching host request/response listeners to the passed pay confirm ActivityIframeView, and resizing this view if necessary.
> Add callback for PayConfirmOpened to pass the ActivityIframeView

- .eslintrc
- src/model/page-config-resolver.js
- src/runtime/analytics-service.js
- src/runtime/basic-runtime.js
- src/runtime/button-api.js
- src/runtime/client-config-manager.js
- src/runtime/entitlements-manager.js
- src/runtime/experiments.js
- src/runtime/runtime.js
- src/ui/loading-view.js
- src/utils/gaa-test.js
- src/utils/gaa.js
- src/utils/style.js
- src/utils/xhr.js
This PR updates src/ code to use for-each loops (easier to control) instead of the forEach method
This PR also allows [spread syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) and [destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment), since IE11 is no longer a concern
> Using for-of instead of forEach in src/ directory

- src/runtime/analytics-service-test.js
- src/runtime/analytics-service.js
This will allow us to pass the swg user token as a url parameter to the service iframe. The swg user token url parameter will be used by the swg user token processor the create a swg reader key (see https://docs.google.com/document/d/1qDJGSwL3Frg9DSLcSnla3GB2gezNF34LaObcf8dcda8/edit?resourcekey=0-Zf6g3V_wDwsbTDgKRQoTNQ#bookmark=id.dbdrtba5n14y). This will be necessary for experiment diversion.
> Adding an optional swg user token param to the analytics service

- src/runtime/client-config-manager-test.js
- src/runtime/client-config-manager.js
fix `skipAccountCreationScreen` client option not propagating to the default `clientConfig`
> Make sure clientOptions propagate into default clientConfig

- src/runtime/pay-flow-test.js
- src/runtime/pay-flow.js
paymentRequest is not present if the pay flow was opened in redirect mode
The productType is needed to open the current version of the payconfirmiframe when the pay flow completes
> Set productType in SubscribeResponse if paymentRequest is not present

- src/runtime/basic-runtime-test.js
- src/runtime/basic-runtime.js
Adds a default `setOnEntitlementsResponse` to the basic runtime that will consume a metered read if an entitlement provided enables the page via metering.
FYI @longmelon @davwood-alpha
> feat(basic-runtime): Setup default entitlements handler to consume metered reads

- src/runtime/basic-runtime-test.js
- src/runtime/basic-runtime.js
- src/runtime/entitlements-manager-test.js
- src/runtime/entitlements-manager.js
Instead of always including metering parameters by default, we should require that a page explicitly opt-in to this functionality. It will be enabled by default for SwG Basic runtime.
> feat: we should explicitly opt-in to Google metering

- src/runtime/entitlements-manager-test.js
- src/runtime/entitlements-manager.js
`sut` querystring is missing in the post entitlement request which causes unwanted scenario that a new user token is created when registering user activity to the metering service.
> Should append `sut` querystring in pingback entitlement request

- src/runtime/contributions-flow-test.js
- src/runtime/contributions-flow.js
- src/runtime/offers-flow-test.js
- src/runtime/offers-flow.js
The `publicationId` querystring is needed for these flows to have the processor running.
> Missing `publicationId` in subscription/contribution flow

- src/runtime/entitlements-manager.js
- src/runtime/meter-toast-api-test.js
- src/runtime/meter-toast-api.js
There are different UIs for the known and unknown meter toasts. In order to display it correctly, we need to pass the MeterType. client_user_attribute is a good indicator whether the given meter is known or unknown.
> Pass MeterType to display the correct toast

- src/utils/gaa-test.js
- src/utils/gaa.js
This PR adds support for the `@graph` construct in ld+json, as @tfbrito mentioned here: https://github.com/subscriptions-project/swg-js/issues/1463#issuecomment-948663088
> Showcase: Support @graph constructs in ld+json

- src/i18n/swg-strings.js
- src/runtime/audience-action-flow-test.js
- src/runtime/audience-action-flow.js
- After completing the regwall: Created an account with [user's email]
- After completing the newsletter signup: Signed up with [user's email] for the newsletter
- If the user has completed the regwall before: Signed in as [user's email]
- If the user has completed the newsletter before: You have signed up before (no change)
Will add more translations once the messages are translated in the TC.
> Update toast messages when user completes an audience action

- src/runtime/runtime-test.js
- src/runtime/runtime.js
Fix for b/221799241.  SwgClassic doesn't always call entitlements before the buy flow, so we should always initialize the analytics service/logging for SwgClassic.
> Initialize analytics service logging for SwG Classic Publishers.

- src/runtime/fetcher.js
The current code caused showing js error in the dev console because we did not properly catch the error when parsing invalid json.
> Fix the js error when parsing invalid json

- src/model/auto-prompt-config.js
- src/runtime/auto-prompt-manager-test.js
- src/runtime/auto-prompt-manager.js
- src/runtime/client-config-manager-test.js
- src/runtime/client-config-manager.js
This change is to support the updated prompt frequency configs:
1. Maximum number of impressions can be capped not only by week. For example, for medium frequency, the maximum number of impressions is 2 per 3 days.
2. Introduce `backoffSeconds` (similar to the dismissal case) to prevent the prompt showing in consecutive page loads.
Internal references: b/226132329, b/226131635
> Use ImpressionConfig instead of maxImpressionsPerWeek for auto prompt

- src/model/auto-prompt-config.js
- src/runtime/auto-prompt-manager-test.js
- src/runtime/auto-prompt-manager.js
- src/runtime/client-config-manager-test.js
- src/runtime/client-config-manager.js
The backend sends `backOffSeconds` instead of `backoffSeconds`. Therefore all the `backoffSeconds` should be updated to avoid confusion.
> Fix naming for backOffSeconds

- src/runtime/basic-runtime-test.js
- src/runtime/basic-runtime.js
- src/runtime/callbacks-test.js
- src/runtime/callbacks.js
- src/runtime/meter-toast-api-test.js
- src/runtime/meter-toast-api.js
For the meter prompt used by basic, when "Become a subscriber" is clicked, the offers flow should be triggered. Previously, `setOnNativeSubscribeRequest` was used for starting the offers flow. There are two issues by this approach:
1. The "View on" native offer card is always displayed.
2. The publisher would not be able to implement its own subscription callback.
This PR introduces a new callback (which is not exposed publicly) and the basic runtime will set it to trigger the "non-native" offer flows. In future, any prompts that want to start the offers flow but doesn't need the native option can use this new callback.
Internal reference: b/227343269
> Add a new callback to trigger the non-native offers flow

- .codecov.yml
Getting codecov failures on very minor drops like 0.01% even when a good set of tests has been added. Seems reasonable to allow for such minor drops when adding new functionality.
> Update CodeCov to allow 0.05% drop in coverage

- src/runtime/basic-runtime-test.js
- src/runtime/basic-runtime.js
This fixes an issue when subscription publications may see a metering prompt for a page that has `isAccessibleForFree` set to true.
We only want to meter the page if we know the page is not accessible.
> fix: metering should only occur for pages that are locked

- src/utils/gaa-test.js
- src/utils/gaa.js
Internal tracking / context: b/229802186
Removing the source parameter appended to authorizationUrl in GaaGoogle3pSignInButton as it is not used by publishers and the current method of getting the source URL (parent.location.href) is causing a cross-origin issue when  GaaGoogle3pSignInButton is hosted in a different origin than the article page. The source parameter is only provided for convenience and publishers can append this on their own with greater flexibility.
> Remove the unused source param in GaaGoogle3pSignInButton

- src/runtime/pay-flow-test.js
- src/runtime/pay-flow.js
TwG flows also do not support the native pay flow. This fixes the issue of TwG opening a failing native Pay view when using the new paySwgVersion.
> Set forceDisableNative to true for paySwgVersion 3

- src/runtime/event-type-mapping.js
Based on the News Tagging Guide: https://newsinitiative.withgoogle.com/training/datatools/ntg?platform=analytics&content=user-engagement__newsletter
> Add Google Analytics events for registration/newsletter sing up

- src/utils/gaa-test.js
- src/utils/gaa.js
- Add native 3P button & authorizationUrl to init function
- Rename clientId with googleApiClientId
- Create promise to wait for window load
- Use existing methods instead of duplicating code
- Avoid duplicate tests by moving some from show to render_
> Add 3P button support to EA API and improvements

- src/runtime/link-accounts-flow-test.js
- src/runtime/link-accounts-flow.js
We need to save the SwgUserToken in the Link Flow. This is implemented in `LinkCompleteFlow` using the `swgUserToken` field passed in the response from the backend.
> Save SwGUserToken in Link Flow

- src/runtime/auto-prompt-manager-test.js
- src/runtime/auto-prompt-manager.js
This allows deps to be passed to getMiniPromptApi in the constructor of AutoPromptManager, so subclasses overriding getMiniPromptApi do not have to handle passing deps.
> Add deps as a parameter of getMiniPromptApi

- src/runtime/runtime-test.js
- src/runtime/runtime.js
IE11 is no longer supported (b/191509852).
> Remove outdated warning for IE11

- src/components/dialog.css
- Increase specificity of selectors to reduce the chance of other page styling taking precedence.
- Use viewport height to avoid falling back to `html` height.
Internal ref: b/244299030
> Improve CSS for disabling content scroll

- src/runtime/client-config-manager-test.js
- src/runtime/client-config-manager.js
- src/runtime/link-accounts-flow-test.js
- src/runtime/services.js
The LinkComplete class was setup to load client configuration but never fetched it.
Due to server changes causing problems (reference b/246641990), this defaults the empty configuration to use the prefix and sets the default of the `feUrl` function to use the prefix
> fix: having the prefix included for empty client default to true

- src/runtime/experiment-flags.js
This PR updates the value of the disable-desktop-miniprompt flag to use kebab case to match the naming conventions of other experiments.
> Update name of disable-desktop-miniprompt flag to kebab case.

- src/runtime/basic-runtime-test.js
- src/runtime/basic-runtime.js
Remove check for secure channel to fix entitlements check on Firefox. When the activity runs as a redirect, it is not considered secure.
b/190614158
> Remove check for secure channel in entitlements check

- src/runtime/audience-action-flow-test.js
- src/runtime/audience-action-flow.js
- src/runtime/entitlements-manager-test.js
- src/runtime/meter-toast-api-test.js
- src/runtime/meter-toast-api.js
Updating the meter toast and audience action iframes to include a URL parameter to identify the developers configured locale for correct translation settings on the server.
Internal bug reference: b/254841680
Images below were from me altering one of the test publication snippets to set `lang` in `clientOptions` to `pt-BR`.
> fix: pass the locale param set by the publisher to the actions iframe

- src/utils/gaa-test.js
- src/utils/gaa.js
This check was a bit redundant, since line 2060 of `src/utils/gaa.js` was already filtering out falsy values
> isAccessibleForFree: Removes check for `null`

- src/runtime/link-accounts-flow-test.js
- src/runtime/link-accounts-flow.js
This PR logs when people successfully link accounts and save subscriptions. Here are the two new events:
- `EVENT_LINK_ACCOUNT_SUCCESS` (from the `linkAccount` flow)
- `EVENT_SAVE_SUBSCRIPTION_SUCCESS` (from the `saveSubscription` flow)
> Log when people successfully link accounts and save subscriptions

- src/runtime/meter-toast-api-test.js
- src/runtime/meter-toast-api.js
internal bug: b/258084894
This should update the meter iframe to only include the URL param for the locale setting when a language is set **and** `forceLangInIframes` is enabled, which defaults to true for `swg-basic` builds.
> Only include the hl param when explicitly set

- src/utils/gaa-test.js
- src/utils/gaa.js
Allows SwG publishers to receive entitlements from GaaMetering.init call.
Internal reference: b/255779232
> Return entitlements to handleSwGEntitlement

- src/api/basic-subscriptions.js
- src/api/subscriptions.js
- src/runtime/basic-runtime-test.js
- src/runtime/basic-runtime.js
- src/runtime/runtime-test.js
- src/runtime/runtime.js
- src/runtime/subscription-linking-flow-test.js
- src/runtime/subscription-linking-flow.js
Add a method to initiate the subscription linking flow. The method opens /linksaveiframe with the appropriate parameters for subscription linking. When the iframe messages the result, it returns the outcome to the caller.
b/236000111
> Add API to initiate subscription linking

- src/utils/url-test.js
- src/utils/url.js
Fix an issue for getCanonicalUrl in AMP when both canonical tag and rootNode.location are undefined by returning an empty string. This was a default behavior prior to https://github.com/subscriptions-project/swg-js/pull/2447
Internal tracking: b/260953276
Branched from amp instead of main in #2541
> Add a fallback for getCanonicalUrl (amp)

- demos/public/link-subscription.html
- demos/public/prod/subscriptions/link-subscription.html
- demos/public/qual/contributions/link-subscription.html
- demos/public/qual/subscriptions/link-subscription.html
- demos/public/subscription-linking.js
Allow specifying a PPID when invoking the subscription linking test flow. Populate the PPID to a random number by default.
Also moves shared logic and HTML structure to shared JS file to reduce duplication.
b/258726652
> [SL] Allow specifying PPID on demo sites

- src/runtime/analytics-service-test.js
This should improve coverage a bit, since no tests were using the extra param
> Remove extra test method param from analytics-service-test.js

- src/utils/gaa-test.js
Lets avoid `expect()` calls within `.then()` callbacks, since that can easily lead to the testing framework ignoring errors that happen after the test finishes. Async/await is a great way to ensure something happens before a test completes
> Fix async tests in gaa-test.js

- src/runtime/runtime-test.js
- Removes the redundant `installRuntime legacy` section, since the same tests exist in the `installRuntime` section  
- Use arrow functions when a flexible `this` value isn't needed
- Shortens test names
- Removes try/catch patterns from tests, since they can cause silent failures, and a few were. Explicitly expect errors/rejects instead
> Improve runtime.js tests

- src/runtime/basic-runtime-test.js
- Shortens test name
- Creates valid entitlement (previous one was crashing test silently)
- Uses more concise `resolves()` method on a stub
- Uses `await` within a normal `expect()` call. The `.eventually` modifier can lead to hidden failures if the preceding `expect()` call isn't awaited, so it might be best to only use `.eventually` for testing promise rejections
> Fixes an async expectation in basic-runtime-test.js

- src/model/doc-test.js
- src/model/page-config-resolver-test.js
- src/model/page-config-writer-test.js
- src/runtime/pay-flow-test.js
- src/runtime/storage-test.js
- src/runtime/subscription-linking-flow-test.js
- Simply `await` promises we expect to succeed
- Only use `.eventually` modifier for testing promise rejections
> Simplify positive async expectations

- src/runtime/analytics-service-test.js
- Adds test for Google Transaction ID experiment
- Removes test for concluded beacon/clearcut experiment
- Removes extra expectation in another test
> Improve coverage in analytics-service.js

- src/runtime/button-api-test.js
- Adds test for bailing gracefully when the `document` is headless
> Improve coverage in button-api.js

- src/runtime/audience-activity-listener-test.js
- Adds test verifying behavior when SUT is missing
> Improve coverage in audience-activity-listener.js

- src/components/dialog.css
Reverts subscriptions-project/swg-js#2560
FYI @justinchou-google this caused a UI issue where it shifts the page when a dialog displays
> Revert "Add position attribute to swg-disable-scroll class to prevent background scrolling on mobile"

- src/components/dialog.css
Original View (no additional css)
View with just `position`
New Changes with both `position` and `width`
New Mobile View, unchanged
> Disable mobile scroll on swg dialog, fix width

- src/utils/log-test.js
- src/utils/log.js
- Removes unused features (`fromAssert`, `associatedElement`, and `messageArray` custom properties on error)
- Cleans up tests (related to #2627)
> Removes unused log features, cleans up tests

- src/runtime/analytics-service-test.js
- src/runtime/audience-action-flow-test.js
- src/runtime/audience-activity-listener-test.js
- src/runtime/auto-prompt-manager-test.js
- src/runtime/basic-runtime-test.js
- src/runtime/button-api-test.js
- src/runtime/deferred-account-flow-test.js
- src/runtime/entitlements-manager-test.js
- src/runtime/link-accounts-flow-test.js
- src/runtime/login-notification-api-test.js
- src/runtime/login-prompt-api-test.js
- src/runtime/meter-toast-api-test.js
- src/runtime/offers-api-test.js
- src/runtime/pay-flow-test.js
- src/runtime/propensity-server-test.js
- src/runtime/runtime-test.js
- src/runtime/subscription-linking-flow-test.js
- src/runtime/wait-for-subscription-lookup-api-test.js
- src/ui/toast-test.js
- Simplifies behavior mocking using `resolves()` and `rejects()` methods
> Use resolves/rejects methods instead of .returns(Promise.re...)

- build-system/eslint-rules/index.js
- build-system/eslint-rules/no-export-side-effect.js
- build-system/tasks/closure-compile.js
- build-system/tasks/jsify-css.js
- build-system/tasks/lint.js
- build-system/tasks/unit.js
- examples/sample-pub/content.js
- examples/sample-pub/metering.js
- examples/sample-pub/publisher.js
- src/runtime/analytics-service.js
- src/runtime/audience-action-flow-test.js
- src/runtime/auto-prompt-manager-test.js
- src/runtime/extended-access/gaa-metering-regwall-test.js
- src/runtime/extended-access/gaa-metering-test.js
- src/runtime/link-accounts-flow-test.js
- src/runtime/meter-toast-api-test.js
- Prefers for/of instead of `forEach`, as Google's JS style guide suggests: [go/js-style#features-for-loops](https://google.github.io/styleguide/jsguide.html#features-for-loops)
- Keeps using `.forEach()` for parameterizing unit tests
- Destructuring params to reduce nesting
> Migrate from `.forEach()` to for/of pattern

- src/runtime/link-accounts-flow-test.js
- src/runtime/link-accounts-flow.js
Internal bug - b/252982870
When handling the linking through a redirect flow, we make the call to block notification handling and unblock when the flow completes, but we do not unblock if the flow had an error (e.g. cancellation). This just makes sure to unblock the notification handler in this case
Bug: 
Fix:
> fix: unblock entitlement notification on linking redirect error

- src/runtime/auto-prompt-manager-test.js
- src/runtime/auto-prompt-manager.js
- src/runtime/entitlements-manager.js
- src/runtime/experiment-flags.js
b/263402383
This implements the logic to serve a Survey prompt before a Contribution prompt given the SurveyTriggeringPriorityExperiment is enabled and passed from the article endpoint. The Survey prompt will be served first, even if there are other Audience Actions configured with a higher priority.
> When experiment SurveyTriggeringPriority from article endpoint is enabled, trigger Survey prompt before Contribution prompt.

- src/runtime/offers-flow-test.js
- src/runtime/offers-flow.js
- src/runtime/services.js
Include the `useNewOfferCard` URL param in the offersiframe URL if there is a value present in #swg.newoffercard.
b/264470652
> Allow forcing the new offer card with #swg.newoffercard

- src/stories/AutoPrompt.stories.js
- Imports `basic-main.js` instead of adding a script to the page (which was 404'ing for me, at least)
- Removes an immediate refresh, since Swgjs will always load right away
- Keeps refreshing when navigating away to another Story, to ensure Swgjs Basic gets a fresh start
> Fix Autoprompt stories

- package.json
- Downgrades `chromedriver` to 108.0.0
> Downgrade Chromedriver to fix e2e tests

- .github/workflows/ci.yaml
- build-system/tasks/e2e.js
- package.json
- Remove E2E retries, so Nightwatch returns an error exit code if it fails to connect with Chromedriver (https://github.com/nightwatchjs/nightwatch/issues/1820)
> Fix stealth E2E failures to connect

- build-system/tasks/args.js
- build-system/tasks/changelog.js
- build-system/tasks/closure-compile.js
- build-system/tasks/compile-config.js
- build-system/tasks/compile.js
- build-system/tasks/internal-version.js
- build-system/tasks/karma.conf.js
- build-system/tasks/lint.js
- build-system/tasks/publish.js
- build-system/tasks/serve.js
- build-system/tasks/unit.js
Parse args before *and* after a `--` divider.
This lets us pass args that some tools (ex: Rollup) reject, by placing those args *after* a `--` divider.
Ex:
```sh
npx rollup --swgArg=1234    # Fails
npx rollup -- --swgArg=1234 # Succeeds w/ this PR
```
> Parse args before and after a `--` divider

- src/api/basic-subscriptions.js
- src/runtime/basic-runtime-test.js
- src/runtime/basic-runtime.js
This method should only be invoked using the original runtime. See b/261874155.
> Remove linkSubscription from basic-runtime

- src/runtime/link-accounts-flow-test.js
- src/runtime/link-accounts-flow.js
- Adds tests
- Renames an existing test
- Updates implementation to call `setTimeout` on `this.win_`, so tests can mock `setTimeout`
> Improve coverage in link-accounts-flow.js

- package.json
- vite.config.js
- yarn.lock
- Production builds still use Closure compiler by default.
- Optionally use Vite + Rollup instead:
- `npx vite build -- --target=basic   # Plus other CLI args`
- `npx vite build -- --target=classic # Plus other CLI args`
- `npx vite build -- --target=gaa     # Plus other CLI args`
> Add Vite + Rollup build system

- .github/workflows/ci.yaml
- Tells CI jobs to run on the latest Ubuntu LTS ([currently 22.04](https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/))
> CI: Run jobs on the latest Ubuntu LTS

- .github/workflows/ci.yaml
- build-system/tasks/e2e.js
- Add new CI task
- Preserve existing E2E CI task with the same name, since the name is part of the `main` branch's rules
- Remove Closure build step from `e2e` task
> E2E test new build system

- .github/workflows/ci.yaml
- test/e2e/pages/basic.js
- test/e2e/pages/extendedAccess.js
- test/e2e/tests/basic.js
- test/e2e/tests/extendedAccess.js
- Adds E2E test verifying Extended Access regwall renders
- Adds E2E test verifying Basic contribution button works
- Builds all Swgjs binaries before Vite E2E tests
> Add E2E tests for Extended Access and Basic binaries

- vite.config.js
- Create sourcemaps for Vite + Rollup builds
- Create Vite plugin that point sourcemaps to a Swgjs release on GitHub
> Vite + Rollup: Create sourcemaps

- src/runtime/auto-prompt-manager-test.js
Tests were intermittently failing after https://github.com/subscriptions-project/swg-js/pull/2750, fixes test to use `AutoPromptType.SUBSCRIPTION`.
> Fix Subscription tests for SecondPromptDelay Experiment

- .github/workflows/ci.yaml
- Tells GitHub to only run a set of `push` CI jobs for the `main` branch (successful merges)
Avoids running CI jobs twice when a PR comes from a branch of the main `swg-js` repo, as seen in this screenshot from #2759:
> Avoid running CI jobs twice

- src/api/subscriptions.js
- src/runtime/experiment-flags.js
- src/runtime/runtime-test.js
- src/runtime/runtime.js
~~@hartmannr76 
We talked about using `subscriptions.configure` for setting experiments on this flag, but it appears that `configure` will run after the endpoint is already decided in `runtime.configured_`.  I think this means that we will need to use an experiment that's either compiled in, use a value in the markup, or add a new method to the runtime. I opted for the last option, and was wondering what you think. With this implementation you will need to add the following to the swg callback: `subscriptions.setExperimentValue('enable_enterprise_article', true);`.~~
Add new config field to set the use of the article endpoint. Needed as part of efforts to open audience actions for enterprise users.
> Add useArticleEndpoint to config

- src/runtime/extended-access/gaa-metering-test.js
- src/runtime/extended-access/gaa-metering.js
Previously (#2771) we made `unlockArticle` optional but not really calling it in a server-side paywall scenario (i.e. when showcaseEntitlement is provided). This change will make `unlockArticle` effective when provided.
- Publishers who unlock articles on the server-side will not be impacted by this change. GAA will initialize a default `unlockArticle: () => {}`.
- Publishers who provide `unlockArticle` will have this method called when `showcaseEntitlement` is consumed.
Ref: b/234314583#5
> Call unlockArticle if provided when consuming showcaseEntitlement

- build-system/tasks/assets.js
- Tries improving code readability
- Removes unnecessary i18n assets (ex: `xlb`, `README.md`) from the `dist/` folder
> Swgjs Release: Remove extra i18n assets

- src/components/friendly-iframe-test.js
- src/utils/style-test.js
- src/utils/style.js
- Removes unused features (ex: vendor prefixing)
- Uses `element.style.setProperty` and `element.style.getPropertyValue`, instead of accessing `element.style` directly (will help with TypeScript migration)
> Simplify `src/utils/style`

- src/components/friendly-iframe.js
- src/runtime/extended-access/gaa-google-sign-in-button.js
- src/runtime/extended-access/gaa-google3p-sign-in-button.js
- src/runtime/extended-access/gaa-metering-regwall.js
- src/runtime/extended-access/gaa-sign-in-with-google-button.js
- src/utils/dom-test.js
- src/utils/dom.js
- Removes unused features (ex: passing `style` attribute to `createElement`)
- Makes types more consistent (will help with TypeScript migration)
> Simplify `src/utils/dom`

- src/runtime/extended-access/gaa-metering-test.js
- src/runtime/extended-access/gaa-metering.js
Reverts subscriptions-project/swg-js#2784
- The removal of subscriptions.init causes issues in showcase entitlement consumption flow (specifically `consumeShowcaseEntitlementJwt` depends on `setOnNativeSubscribeResponse` which awaits for SwG to be initialized)
- To create a separate PR that addresses the issue described in subscriptions-project/swg-js#2784 with an alternative solution.
Internal tracking: b/271063736
> Revert "Remove redundant subscriptions.init() from EA API"

- build-system/transform-define-constants.js
- src/constants.ts
- Brings back a modified version of the `build-system/transform-define-constants.js` script
- Simplifies exports in `src/constants.ts`
> Transform constants for Babel builds (local demo & storybook)

- src/runtime/audience-action-flow-test.js
- src/runtime/audience-action-flow.js
- src/runtime/entitlements-manager-test.js
- src/runtime/entitlements-manager.js
Adds `onResult` support in `AvailableIntervention`. This replaces `setOnInterventionComplete` which was originally planned to be used for "Funnel Prompts for Enterprise". This was chosen to simplify the API for third parties.
> Add onResult to AvailableIntervention.

- src/components/dialog-manager.ts
- src/components/dialog.ts
- src/components/graypane-test.js
- src/components/graypane.ts
- Requires `animated` param for `show()` method
Note: One alternative approach would be adding a new test verifying the method's default behavior when no arg is passed. I kinda prefer the callsite clarity of passing an arg along with a comment though (`graypane.show(/* animated */ true)`)
> Improve coverage in `src/components/graypane`

- tsconfig.json
- vite.config.js
- Disable TS `useDefineForClassFields` compiler option (required polyfills)
- Bring back property name mangling
| Bundle | Before | After | Diff |
| :--- | :---: | :---: | :---: |
| Swgjs Basic | 65,122 B | 61,090 B | -4,032 B |
| Swgjs Classic | 61,484 B | 57,820 B | -3,664 B |
| Swgjs Extended Access | 20,794 B |  20,499 B | -295 B |
> Build: Bring back property name mangling

- src/runtime/basic-runtime-test.js
- src/runtime/basic-runtime.js
- src/runtime/experiment-flags.ts
This flag was used for switching the basic runtime to the article endpoint, and has been fully launched since March 2022.
Tests were updated to stub getEntitlements before creating the ConfiguredBasicRuntime instance, as with this change getEntitlements is always called by the ConfiguredBasicRuntime constructor.
b/276458173
> Clean up use-article-endpoint experiment flag

- src/runtime/experiment-flags.ts
- src/runtime/runtime-test.js
- src/runtime/runtime.js
This does not change any behavior in prod but allows us to begin testing usage of the new endpoint.
b/247809038
> Add experiment flag to use /article endpoint for Classic

- src/runtime/experiment-flags.ts
There are no code references to this flag. It was marked deprecated in 2019.
Also includes some formatting auto-fixes.
> Remove deprecated experiment flag CONTRIBUTIONS

- src/runtime/experiment-flags.ts
There are no references. Doesn't look like this one was ever used.
> Remove unused propensity experiment flag

- src/runtime/pay-client-test.js
Adds a test covering https://github.com/subscriptions-project/swg-js/blob/9d3b184791937593c221e585e508e5338786aa76/src/runtime/pay-client.js#L258
> Improve coverage in `src/runtime/pay-client-test`

- src/api/client-event-manager-api.ts
- src/runtime/analytics-service-test.js
- src/runtime/analytics-service.ts
- src/runtime/auto-prompt-manager-test.js
- src/runtime/client-event-manager.ts
Saves the current timestamp when an event is queued, instead of when the event is sent
> Queue events with timestamps

- src/runtime/audience-action-flow-test.js
- src/runtime/audience-action-flow.ts
event_category and event_label are default dimensions that are supported in Universal Analytics. Since UA will be deprecated in July 1, 2023, and thus we expect our clients to migrate to GA4, adding more custom dimensions in preparation for deprecating the default dimensions.
> Support additional custom dimensions for survey submission events for Google analytics

- src/runtime/basic-runtime-test.js
- src/runtime/basic-runtime.ts
- src/runtime/runtime-test.js
- src/runtime/runtime.ts
These `ready_` Promises have existed since the beginning, but it seems like they were never used? This PR cleans them up
> Remove extra `ready_` Promise from runtimes

- test/e2e/pages/smartButton.js
This feature is fully launched, the experiment flag is no longer in use.
Also remove commented code.
> Remove launched exp flag from smartbox test

- src/runtime/auto-prompt-manager-test.js
Test behavior is the same, just asserting that the subscription should be displayed over other audience actions.
> Fix action order in tests to accurately assert subscription priority

- src/runtime/auto-prompt-manager-test.js
- src/runtime/auto-prompt-manager.ts
No-op refactor to simplify AutoPromptManager:
- Move determination of largePromptFn to separate method to make showAutoPrompt_ slightly smaller.
- Remove displayLargePromptFn from ShowAutoPromptParams. This was only used by test paths.
> Simplify usage of largePromptFn in AutoPromptManager

- src/runtime/auto-prompt-manager.ts
Remove this method. It was intended to be overridden by subclasses but is now marked private. AutoPromptManager is not otherwise designed for subclassing and is never subclassed. Plus this removes a typo.
> AutoPromptManager: Remove getMiniPromptApi_

- src/runtime/auto-prompt-manager-test.js
- src/runtime/auto-prompt-manager.ts
- src/runtime/contributions-flow-test.js
- src/runtime/contributions-flow.ts
- src/runtime/offers-flow-test.js
- src/runtime/offers-flow.ts
Do not check the predicate in OffersFlow/ContributionsFlow. Update AutoPromptManager so it does not show the prompt when false.
Updates the test case in AutoPromptManager that missed a path that would still show the prompt when the flag is false.
b/282759151
> Correct check for canDisplayAutoPrompt

- package.json
- src/runtime/experiment-flags.ts
- test/e2e/nightwatch.conf.js
- test/e2e/pages/basic.js
- test/e2e/pages/contribution.js
- test/e2e/pages/manualInitialization.js
- test/e2e/pages/publication.js
- test/e2e/pages/smartButton.js
- test/e2e/util.js
Add nightwatch env that runs test with all flags enabled. It can be run in isolation with `npx gulp e2e --env=all_experiments_enabled` and is included in the e2e npm script.
The new test configuration currently fails, as expected, due to b/282759151. Will wait to merge until this is fixed.
b/283467774
> Add e2e test configuration enabling all experiment flags

- src/runtime/audience-action-flow-test.js
- src/runtime/audience-action-flow.ts
b/285143702. 
Send survey response data along with the following default dimensions for GA4: content_id, content_group, content_type
It will allow publishers to use data studio template without setting up custom dimensions.
> Send additional params for survey responses in GA4 default dimensions

- src/runtime/runtime-test.js
- src/runtime/runtime.ts
Move this logic so the config is populated even if `start` is not called. b/286924363.
> Move logic to populate client config to getEntitlements

- src/runtime/audience-action-flow-test.js
- src/runtime/audience-action-flow.ts
The survey transfer event is not logged in the case where only gtm logging is available. This fixes that.
> Allow survey transfer events to be logged when gtm is eligible.

- src/api/subscriptions.ts
- src/runtime/runtime-test.js
- src/runtime/runtime.ts
Return the result of calling LinkSaveFlow.start. b/288363669.
> Fix returning completion status from saveSubscription

- src/runtime/extended-access/gaa-metering-regwall-test.js
- src/runtime/extended-access/gaa-metering-regwall.ts
Add check so multiple calls to GAAMeteringRegwall.show do not install duplicate event handlers. Speculative fix for b/281908268.
> Ensure GAA regwall event handlers are only added once

- src/ui/ui-css.ts
`overflow: hidden` on body element is one of the common techniques to disable scroll. It works in most web sites, but might not work in few cases.
`position: fixed` seems to guaranteed scroll is always disabled by fixing the page to the top. However, there's a side effect of sending readers to the top of the page which is considered as a bug.
To fix the issue, removing `position: fixed` from the css class, acknowledging disabling scroll is not 100% guaranteed.
Refer to b/291067040 for more context.
Demo: https://screencast.googleplex.com/cast/NTk3MDY0NDE4NjQzMTQ4OHxiODU0NjhmZS02Yg
> Do not fix page to the top when scroll is disabled

- src/runtime/auto-prompt-manager-test.js
b/291598463
Given the mini prompt is still in use by a small number of contribution and subscription publishers, we do not want to fully deprecate miniPromptApi at this point (https://github.com/subscriptions-project/swg-js/pull/3119 on hold).
This change refactors some of the tests to more clearly show when the mini prompt is expected to start and when it isn't. This change also reorders like-tests to be grouped together.
> Small cleanup of miniprompt tests

- package-lock.json
- package.json
- vite.config.js
Add Vite plugin to wrap generated code in outer function to avoid adding to global scope.
Revert override of esbuild version as this workaround tolerates the case where lowered code writes top-level vars.
Fixes b/293444391.
> Wrap compiled JS in outer IIFE to avoid leaking vars to global scope

- src/runtime/auto-prompt-manager-test.js
- src/runtime/auto-prompt-manager.ts
- src/runtime/basic-runtime-test.js
b/291598203
Previously, revenue model was required in the code snippet. After the Premonetization launch, the `autoPromptType` parameter was deprecated from the code snippet, and the revenue model was inferred from the article response. As such, swg.js still supported both cases: when `Contribution` or `Subscription` was a valid action in the article, and when it was not. 
This change simplifies `autoPromptManager` and removes the backwards compatibility; all Contribution and Subscription publishers are assumed to have respective valid Contribution and Subscription actions in their article responses. If the `autoPromptType` param is provided, this is used to denote the mini prompt api is eligible.
> Enforce monetization actions to be in article response

- .github/workflows/ci.yaml
Upload VRT artifacts in GitHub CI runs so they are available for debugging.
The uploaded HTML will not be directly usable until https://github.com/nightwatchjs/nightwatch-vrt/pull/4 is released, but in the meantime the uploaded images can show why a test failed.
b/296120391
> Upload VRT report for GitHub CI runs

- build_and_run_e2e.sh
- package.json
Fix e2e command so it reports failure if default config fails, but all_experiments_enabled passes.
b/296404968
> Fix exit status of e2e command if default run fails

- build_and_run_e2e.sh
Allows updating VRT goldens via
`npm run e2e -- --update-screenshots`.
b/294885021
> Update e2e script to pass args through to nightwatch

- src/runtime/basic-runtime-test.js
- src/runtime/basic-runtime.ts
- src/runtime/experiment-flags.ts
- src/runtime/runtime-test.js
- src/runtime/runtime.ts
- test/e2e/nightwatch.conf.js
Remove references to the populate-client-config-classic flag, which has been fully launched since June 22.
Also updates basic-runtime to remove a call to fetch the client config, this is redundant because the call to runtime.start populates the config.
b/280305573
> Remove references to populate-client-config-classic flag

- demos/public/prod/subscriptions/button-french.html
- demos/public/prod/subscriptions/button-light.html
- demos/public/qual/contributions/button-dark.html
- demos/public/qual/subscriptions/button-dark.html
- demos/public/qual/subscriptions/button-french.html
- demos/public/qual/subscriptions/button-light.html
Disable autoprompts, since the prompts are invoked manually via a button on these pages. Otherwise, prompts can be shown manually, then loaded again as autoprompts.
> Disable autoprompts for demo pages using buttons

- src/runtime/auto-prompt-manager.ts
b/300963305
CTA prompts do not trigger local storage actions, i.e. already working as intended.
> Cleanup TODO for CTA should not affect frequency capping local storage

- src/runtime/audience-action-local-flow.ts
- src/runtime/audience-action-local-flows-test.js
- src/runtime/audience-action-local-ui.ts
https://screencast.googleplex.com/cast/NTQ1NjY0Mzk0ODAxOTcxMnw5MzVmMjQ3NC1iZg
> Add close button to newsletter publisher prompt

- src/runtime/audience-action-local-flow.ts
- src/runtime/audience-action-local-ui.ts
There is an issue with text scaling, so we want to use static sizes for now while we investigate how to implement it without being affected by the host page changes.
b/309984044
Also, while it shouldn't be necessary, slightly increased the timeout time just in case.
> Temporarily use fixed text size for rewarded ads

- src/runtime/audience-action-local-flow.ts
Some banners appear over our prompt. This changes the position of our prompt to give it more priority. Screenshots in the bug.
b/310016253
> Change rewarded ad z-index and document placement to put above other banners

- src/runtime/auto-prompt-manager.ts
This adds a delay to dismissible rewarded ad prompts rendering similar to surveys. The side goal of this change is to increase the odds that our prompt is rendered on top of others.
Previous change: https://github.com/subscriptions-project/swg-js/pull/3296
b/310016253
> Add delay to dismissable rewarded ads

- src/i18n/swg-strings.ts
- src/runtime/audience-action-local-flow-test.js
- src/runtime/audience-action-local-flow.ts
Check the article endpoint flags instead of the runtime flags for rewarded ads experiments. Tested locally with the study ramped in qual.
Also a quick side fix for a typo introduced here:
https://github.com/subscriptions-project/swg-js/pull/3321#issuecomment-1823602061
Current workflow of updating the strings manually really isn't ideal.
> Check article flags for Rewarded Ads

- src/runtime/audience-action-local-flow.ts
- test/e2e/pages/enterpriseContribution.js
- test/e2e/tests/enterpriseContribution.js
This decreases the z-index by 1 so that it will appear below other items with the max z-index, like the anchor banner in the screenshot below. This changes the behavior to match our other prompts, and was decided by PM.
Bug: b/318516613
Screenshot:
https://github.com/subscriptions-project/swg-js/assets/106177651/bb25933f-b89a-4a46-9a32-ed6b4597805e
> Update z-index for local audience action to match other prompts

- src/runtime/auto-prompt-manager-test.js
- src/runtime/auto-prompt-manager.ts
b/326050380
Verified the timestamp is being stored, and refreshing to hit global frequency cap does not trigger next prompt. https://screenshot.googleplex.com/4nPH8GJeY2intJt
> Adds BYOP and Rewarded Ad impressions to prompt frequency capping flow.

- src/runtime/auto-prompt-manager-test.js
- src/runtime/auto-prompt-manager.ts
- src/runtime/experiment-flags.ts
- src/utils/constants.ts
b/325512188.
Guarded by new flag. If enabled, this flow will take precedence over the impression based flow.
> Computes frequency cap based on dismissal timestamps instead of impressions.

- src/components/dialog-manager-test.js
- src/components/dialog-manager.ts
- src/components/dialog-test.js
- src/components/dialog.ts
- src/runtime/runtime.ts
Use the article experiment flag as an article experiment flag instead of an client experiment flag.
> Fix enableBackgroundClick experiment

- src/proto/api_messages-test.js
- src/proto/api_messages.ts
- src/runtime/analytics-service-test.js
- src/runtime/analytics-service.ts
- src/utils/url-test.js
b/325082835
Propagate what is written in the page config. During init, we already fallback to product id if isAccessibleForFree is null. https://github.com/subscriptions-project/swg-js/blob/b97b5eb0b10f77899821c3204ebe67db56fad83f/src/runtime/basic-runtime.ts#L230
> Add isLockedContent to analytics context for swg client event logging

- src/runtime/auto-prompt-manager-test.js
- src/runtime/auto-prompt-manager.ts
b/333536312
adds attribute promptIsFromCtaButton when cta button to show prompt is clicked, used to not record impression timestamp
> Does not record impression timestamp for prompts triggered by CTA button

- src/runtime/auto-prompt-manager.ts
> Clean up AutoPromptManager vars to be class attributes

- src/runtime/entitlements-manager-test.js
- src/runtime/entitlements-manager.ts
Add preview config id into article query param.
Tested locally: https://screenshot.googleplex.com/6wBmmrUshWVzWRh.
previewConfigId is needed to render onsite preview.
corresponding query param in article endpoint was added in cl/635907293.
[go/rrm-onsite-preview-dd](http://go/rrm-onsite-preview-dd)
> Add previewConfigId in article query param

- demos/public/prod/enterprise/enterprise-funnel-manual.html
- src/runtime/entitlements-manager-test.js
- src/runtime/entitlements-manager.ts
- src/runtime/runtime-test.js
- src/runtime/runtime.ts
We have a race condition between `start` and `getAvailableInterventions` where `start` will not necessarily call `getEntitlements` before it's needed by `getAvailableInterventions`. This change removes the need to call `start` by having `getAvailableInterventions` make its own call.
This will not duplicate the network call, as the entitlements manager will keep one promise until `reset` has been called. Additionally `start` will not even make a `getEntitlements` call on unlocked content, so we need to remove our dependency on it either way.
Tested manually on the `enterprise-funnel.html` and `enterprise-funnel-manual.html` pages.
> Await on getEntitlements in getAvailableIntervention

- src/runtime/auto-prompt-manager-test.js
- src/runtime/auto-prompt-manager.ts
- src/runtime/entitlements-manager.ts
- src/runtime/experiment-flags.ts
Preview flas was added in cl/636919307.
previewEnabled param was added in Article in cl/634864138.
[go/rrm-onsite-preview-dd](http://goto.google.com/rrm-onsite-preview-dd)
> Bypass UiPredicates, entitlements and frequency capping when onsite preview should be rendered

- src/runtime/audience-action-flow-test.js
- src/runtime/audience-action-flow.ts
- src/runtime/auto-prompt-manager-test.js
- src/runtime/auto-prompt-manager.ts
Interaction is disabled when interacting with regwall, newsletter and survey prompts:
https://screencast.googleplex.com/cast/NDgyMjk2NjA5MjE2OTIxNnw3YzVhZjBlMy1iNg
This is the initial GA requirements for preview prompts, see meeting notes: https://docs.google.com/document/d/1nKszFDK1yh6gdIrsXZfL5cxrbsuNKDJhrNmN6iNKRKc/edit?resourcekey=0-lS48WOcp33v5-9AeEuvZVA&tab=t.0#heading=h.g2mtcg3lwi4u
With interaction disabled, we don't need to worry about completion & google sign in flow or the survey data transfer for now.
> Render preview for regwall, newsletter and survey prompts

- src/runtime/entitlements-manager-test.js
- src/runtime/entitlements-manager.ts
Design doc: [go/rrm-onsite-preview-security-key](http://goto.google.com/rrm-onsite-preview-security-key)
We are passing this key to verify whether the preview access is eligible.
> Add previewKey in article query param based on url param

- demos/public/prod/enterprise/enterprise-funnel.html
- package-lock.json
- package.json
- src/api/available-intervention-test.js
- src/api/available-intervention.ts
- src/runtime/audience-action-flow-test.js
- src/runtime/audience-action-flow.ts
- src/runtime/entitlements-manager-test.js
> Add suppressToast option to intervention api

- src/ui/ui-css.ts
b/359650290
Implemented by adjusting the margin (`margin-inline-start`, which adapts to LTR/RTL, vs. `left` and `right` attributes), as `right: 0px !important` seems to be set deep in the html element. See https://screenshot.googleplex.com/4fzFTCaghPxQh8i
Tested by adding `dir="rtl"` to the HTML.
Before:
After:
Confirming LTR is not impacted:
> Fix intervention position on RTL pages

- src/ui/ui-css.ts
`margin-inline-start` value was not being parse properly.
Before: https://screenshot.googleplex.com/BMWByjs5gAiGpcn
After: https://screenshot.googleplex.com/6wAKYJmTC9C8BK9
> Fix css value for margin-inline-start for tablet/medium screens.

- src/runtime/auto-prompt-manager-test.js
- src/runtime/auto-prompt-manager.ts
Changes:
- Updates condition to NOT log frequency capping events to be when `contentType === CLOSED`.
- Updates timestamps fetched for global frequency cap to include Completion timestamps of the same type as the next action. This is to account for repeatable actions.
- Fixes params to a miniprompt logging test.
b/369191528
> Update frequency capping conditions on ContentType, Repeatability

- src/runtime/auto-prompt-manager-test.js
- src/runtime/auto-prompt-manager.ts
b/376451935
After enabling a CTA as repeatable, it will continue to be returned in `audienceActions` of the article response even after completions. As such, even if a CTA config is missing any repeatabiltiy config, we still need to honor any number of completions recorded.
Added some fallback logic for `FINITE` repeatability count.
> [FPA M0.5] Handle number_of_completions count when CTA Repeatability is not specified.

- demos/public/demos.js
- demos/public/prod/inactive/newsletter.html
- demos/public/prod/subscriptions/newsletter.html
- demos/public/qual/contributions/newsletter.html
- demos/public/qual/subscriptions/newsletter.html
b/372070992
- https://swgjs-demos.wl.r.appspot.com/qual/subscriptions/newsletter.html
- https://swgjs-demos.wl.r.appspot.com/qual/contributions/newsletter.html
- https://swgjs-demos.wl.r.appspot.com/prod/inactive/newsletter.html
- https://swgjs-demos.wl.r.appspot.com/prod/subscriptions/newsletter.html
- https://swgjs-demos.wl.r.appspot.com/newsletter.html
> Adds demo pages for newsletter CTA

- package-lock.json
- package.json
- src/runtime/auto-prompt-manager-test.js
- src/runtime/auto-prompt-manager.ts
- src/runtime/experiment-flags.ts
When experiment 'dismissibility_cta_filter_experiment' is enabled, allow autoprompt to filter out CTAs that the reader can't interact with if they're dismissible. 
Dismissibility: either the funnel is open content, or the CTA itself is marked dismissible.
> Hide dismissible monetary CTAs if reader cannot purchase when experiment enabled

- src/runtime/audience-action-local-flow-test.js
- src/runtime/basic-runtime-test.js
- src/runtime/basic-runtime.ts
- src/runtime/entitlements-manager.ts
- src/runtime/meter-toast-api-test.js
- src/runtime/meter-toast-api.ts
This will 
1. open the login if user clicks the "Already a subscriber" button on meter iframe.
2. show a "Not a subscriber" toast if user is not a subscriber.
This will correspond to cl/730570265.
> Handle "Already a subscriber" click on meter iframe

- src/api/available-intervention.ts
- src/proto/api_messages-test.js
- src/proto/api_messages.ts
- src/runtime/audience-action-flow-test.js
- src/runtime/audience-action-flow.ts
- src/runtime/auto-prompt-manager-test.js
- src/utils/url-test.js
Add the terms and consent info to the onResult callback for API users.
Also adjusted some tests and added a few unrelated api_messages.ts fields that got missed.
b/406212787
> Add consent information to onResult data for opt-ins

- src/runtime/auto-prompt-manager-test.js
- src/runtime/auto-prompt-manager.ts
b/355027865
Add additional step to save frequency capping impressions, dismissals, and completions by configId. This will be used in FCA Phase1, the implementation to Read from this path while determining action eligibility will come later with this launch. 
Some safe guards are added to ensure configId is valid to write, as well as adds checks for when swgjs is in dev or demo mode (via `params.alwaysShow`, or onsite preview).
> FCA Phase 1: Dual Write Frequency Capping events to LocalStorage, keyed by ConfigId

- src/@types/globals.d.ts
- src/runtime/extended-access/gaa-sign-in-with-google-button-test.js
- src/runtime/extended-access/gaa-sign-in-with-google-button.ts
With this change, this resolves the issue in that the sign in button gets stuck with a blank pop-up window caused by severed connection between windows in the metering demo. More reading on the solution here: https://developers.google.com/identity/gsi/web/guides/fedcm-migration
Potential cause of the issue is documented here:
https://developers.google.com/identity/gsi/web/guides/get-google-api-clientid#cross_origin_opener_policy
Screencast showing the change: https://screencast.googleplex.com/cast/NTk3NTQ4NjkyNzczMjczNnw0NzNhNDlmYy1hNg
> Add option to use FedCM for the sign in button in metering demo

- src/runtime/basic-runtime-test.js
- src/runtime/basic-runtime.ts
Only render when experiment is enabled
Tested locally: https://screenshot.googleplex.com/BwwHpzp59R677Z8
> Render inline cta in basic runtime. 

- src/runtime/inline-cta-api-test.js
- src/runtime/inline-cta-api.ts
Inline CTA alpha will not support rewaded ad and byo cta: [go/rrm-inline-cta-alpha-dd](http://goto.google.com/rrm-inline-cta-dd)
> Not render Rewarded ad and byo cta for inline CTA

- src/runtime/subscription-linking-flow-test.js
- src/runtime/subscription-linking-flow.ts
Use the old query string parameter (ppid) for the currently released subscription linking workflow.  This causes the system to render the old UI instead of the new UI (which is not yet approved).
> Render old UI for Subscription Linking

- src/api/subscriptions.ts
- src/runtime/runtime.ts
Add new API for multi publication SL.  Clearly mark it as released for testing purposes only.
> Add SL API for testing purposes

- src/runtime/auto-prompt-manager.ts
When the monetization cta is used as an alternate action, it uses the dismissal settings of the CTA that it was diverted from. We decided that it should continue to use its own.
Tested locally, but don't have a good way to write a test for this right now.
b/425609829
> Add isMonetizationClosable_

- src/runtime/inline-cta-api-test.js
- src/runtime/inline-cta-api.ts
Will disable using event manager for logging for now, and see if it works.
https://source.corp.google.com/piper///depot/google3/java/com/google/subscribewithgoogle/client/ui/common/analytics/analytics_service.ts;l=661-663
Will add it back in following prs when analytics contexts are passed.
> not use event manager to log inline cta events

- src/runtime/audience-action-flow-test.js
- src/runtime/audience-action-flow.ts
- src/utils/url-test.js
- src/utils/url.ts
`google_adtest` is needed to specify if an ad is just for testing. Obviously we don't want it for launch, but I want it just in case for our own testing, and if a publisher asks about it we can provide them this as a workaround until we come up with a more permanent solution.
b/425382590
> Make google_adtest configurable through query param

- src/runtime/auto-prompt-manager-test.js
- src/runtime/auto-prompt-manager.ts
- src/runtime/experiment-flags.ts
Once "purchase unavailable in this region" error screen is supported in contribution CTA, auto prompt manager should consider non-dismissible contribution CTAs regardless of reader region.
> Add flag to show blocking monetary CTAs regardless of reader's region

- src/i18n/swg-strings.ts
- src/i18n/translation.ts
- src/runtime/audience-action-flow.ts
- src/runtime/audience-action-local-flow.ts
- src/runtime/basic-runtime.ts
- src/runtime/button-api.ts
- src/runtime/extended-access/gaa-google-sign-in-button.ts
- src/runtime/extended-access/gaa-google3p-sign-in-button.ts
- src/runtime/extended-access/gaa-metering-regwall.ts
- src/runtime/extended-access/gaa-sign-in-with-google-button.ts
- src/runtime/mini-prompt-api.ts
- src/utils/cta-utils.ts
- src/utils/i18n.ts
Added assert to translation mapping that english is always provided, removing the need to check msg's return type. Also removed the `LANG_MAP` postfix to standardize the field names.
b/421830895
> Translation typing cleanup
